window.chara=[
                       
            // -------------------------------------------------------------------------------- 
                                              // 5 STAR CARDS
            // -------------------------------------------------------------------------------- 
            
      {
          "id": "10015",
          "name": "Randou, Martial Arts Expert",
          "type": "heart",
          "class": "DEF",
          "rare": "5",
          "power": "1012",
          "hp": "554",
          "atk": "100",
          "sp": "301",
          "def": "327",
          "spd": "75",
          "maxpower": "",
          "maxhp": "",
          "maxatk": "",
          "maxsp": "",
          "maxdef": "",
          "maxspd": "",
          "skill1img": "100029",
          "skill1name": "Life Force Tread",
          "skill1": "50% chance to Paralyze target row for 1 turn. 80% chance to lower ATK by 25% for 3 turns",
          "skill1cd":  "70",
          "skill2img": "100030",
          "skill2name": "Hate Fish Summoning",
          "skill2": "Deal 120% SP to target row",
          "skill2cd":  "100",
          "autoname1": "ATK Damage Resistance (B)",
          "auto1": "Increases Resistance against ATK Damage taken by 20%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg1": "ATKDMGresist",
          "autoname2": "Paralyze Resistance",
          "auto2": "Increases Resistance against Paralyze Status by 100%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg2": "PARAresist",
          "autoname3": "Imitation Genius",
          "auto3": "Increases guard percentage by 30%<br><hz>Duration:</hz> 2 turns <hz>Condition:</hz> when HP drops under 50% <hz>Chance:</hz> 100%",
          "autoimg3": "GUARDup",
          "autoname4": "Damage up (B)",
          "auto4": "Increases Damage given by 20%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg4": "DMGup",
          "autoname5": "Damage Reduction (B)",
          "auto5": "Reduces Damage taken by 20%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg5": "DMGresist",
          "lead": "Heart Type DEF +15%",
          "rank": "G"
            },
            {
          "id": "10023",
          "name": "Rinku, Magical Child",
          "type": "yang",
          "class": "ATK",
          "rare": "5",
          "power": "1056",
          "hp": "523",
          "atk": "418",
          "sp": "104",
          "def": "261",
          "spd": "123",
          "maxpower": "",
          "maxhp": "",
          "maxatk": "",
          "maxsp": "",
          "maxdef": "",
          "maxspd": "",
          "skill1img": "100055",
          "skill1name": "Serpent Yo-Yo",
          "skill1": "Deal 85% ATK to the front column. 40% chance to Paralyze for 1 turn",
          "skill1cd":  "110",
          "skill2img": "100056",
          "skill2name": "Nimble Body",
          "skill2": "Own row ATK +65% for 3 turns. +2 Basic Attack Dodge to self",
          "skill2cd":  "60",
          "autoname1": "Paralyze Resistance",
          "auto1": "Increases Resistance against Paralyze Status by 100%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg1": "PARAresist",
          "autoname2": "ATK up (B)",
          "auto2": "Increases own ATK by 25%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg2": "ATKup",
          "autoname3": "Favorite Technique",
          "auto3": "Casts Critical Hit effect on self<br><hz>Duration:</hz> 1 turn <hz>Condition:</hz> when defeats an enemy <hz>Chance:</hz> 80%",
          "autoimg3": "CRITeffect",
          "autoname4": "Damage up (B)",
          "auto4": "Increases Damage given by 20%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg4": "DMGup",
          "autoname5": "Damage Reduction (B)",
          "auto5": "Reduces Damage taken by 20%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg5": "DMGresist",
          "lead": "Yang Type ATK +15%",
          "rank": "G"
      },
      {
          "id": "10035",
          "name": "Jin, Wind User",
          "type": "heart",
          "class": "ATK",
          "rare": "5",
          "power": "1049",
          "hp": "518",
          "atk": "415",
          "sp": "103",
          "def": "258",
          "spd": "141",
          "maxpower": "14828",
          "maxhp": "7392",
          "maxatk": "5924",
          "maxsp": "1472",
          "maxdef": "3684",
          "maxspd": "524",
          "skill1img": "100083",
          "skill1name": "Tornado Fist",
          "skill1": "Deal 270% ATK one enemy",
          "skill1cd":  "100",
          "skill2img": "100084",
          "skill2name": "Wind Barrier",
          "skill2": "Own column ATK +43% for 3 turns. +2 Basic Attack Dodge to self",
          "skill2cd":  "51",
          "autoname1": "ATK up (B)",
          "auto1": "Increases own ATK by 25%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg1": "ATKup",
          "autoname2": "Stun Resistance (B)",
          "auto2": "Increases Resistance against Stun status by 100%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg2": "STUNresist",
          "autoname3": "Great Wind Protection",
          "auto3": "80% chance to reduce one enemy's ATK Damage Resistance by 30%<br><hz>Duration:</hz> 2 turns <hz>Condition:</hz> after using a special <hz>Chance:</hz> 50%",
          "autoname4": "Damage up (B)",
          "auto4": "Increases Damage given by 20%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg4": "DMGup",
          "autoname5": "Damage Reduction (B)",
          "auto5": "Reduces Damage taken by 20%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg5": "DMGresist",
          "lead": "Heart Type ATK +15%",
          "rank": "G"
      },
      {
          "id": "10037",
          "name": "Toya, Curse Ice User",
          "type": "body",
          "class": "SP",
          "rare": "5",
          "power": "1035",
          "hp": "410",
          "atk": "102",
          "sp": "539",
          "def": "179",
          "spd": "105",
          "maxpower": "14665",
          "maxhp": "5852",
          "maxatk": "1452",
          "maxsp": "7692",
          "maxdef": "2556",
          "maxspd": "390",
          "skill1img": "100087",
          "skill1name": "Ice Cutlass",
          "skill1": "Deal 270% SP one enemy",
          "skill1cd":  "100",
          "skill2img": "100088",
          "skill2name": "Shards of Winter",
          "skill2": "Deal 128% SP to the front column with a 40% Chance to Freeze for 1 turn",
          "skill2cd":  "98",
          "autoname1": "Freeze Resistance (B)",
          "auto1": "Increases Resistance against Freeze Status by 100%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg1": "FREEZEresist",
          "autoname2": "SP up (B)",
          "auto2": "Increases own SP by 25%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg2": "SPup",
          "autoname3": "Ice Crystal Protection",
          "auto3": "100% chance to Freeze one enemy<br><hz>Duration:</hz> 1 turn <hz>Condition:</hz> when has a status effect <hz>Chance:</hz> 100%/2 times",
          "autoimg3": "FREEZEchance",
          "autoname4": "Damage up (B)",
          "auto4": "Increases Damage given by 20%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg4": "DMGup",
          "autoname5": "Damage Reduction (B)",
          "auto5": "Reduces Damage taken by 20%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg5": "DMGresist",
          "lead": "Body Type SP +15%",
          "rank": "G"
},
      {
          "id": "10043",
          "name": "Shishiwakamaru, Beautiful White Blade",
          "type": "yin",
          "class": "ATK",
          "rare": "5",
          "power": "1045",
          "hp": "518",
          "atk": "414",
          "sp": "103",
          "def": "259",
          "spd": "106",
          "maxpower": "14815",
          "maxhp": "7392",
          "maxatk": "5912",
          "maxsp": "1472",
          "maxdef": "3696",
          "maxspd": "394",
          "skill1img": "100103",
          "skill1name": "Shukuchi",
          "skill1": "Own column Crit Chance +43% for 3 turns. +2 Basic Attack dodge to self",
          "skill1cd":  "51",
          "skill2img": "100104",
          "skill2name": "Chorus of a Thousand Skulls",
          "skill2": "Deal 128% ATK to front column with a 65% chance to inflict 10% Poison",
          "skill2cd":  "98",
          "autoname1": "Critical up (B)",
          "auto1": "Increases Critical hit chance by 20%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg1": "CRITup",
          "autoname2": "Blind Resistance (B)",
          "auto2": "Increases Resistance against Blind status by 100%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoname3": "Evil Sword's Dance",
          "auto3": "Increases own ATK by 50%<br><hz>Duration:</hz> 2 turns <hz>Condition:</hz> at the start of the WAVE <hz>Chance:</hz> 100%",
          "autoimg3": "ATKup",
          "autoname4": "Damage up (B)",
          "auto4": "Increases Damage given by 20%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg4": "DMGup",
          "autoname5": "Damage Reduction (B)",
          "auto5": "Reduces Damage taken by 20%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg5": "DMGresist",
          "lead": "Yin Type ATK +15%",
          "rank": "G"
      },
      {
          "id": "10044",
          "name": "Beautiful Suzuki, Clown",
          "type": "dex",
          "class": "DEF",
          "rare": "5",
          "power": "1045",
          "hp": "570",
          "atk": "103",
          "sp": "310",
          "def": "337",
          "spd": "100",
          "maxpower": "",
          "maxhp": "",
          "maxatk": "",
          "maxsp": "",
          "maxdef": "",
          "maxspd": "",
          "skill1img": "100105",
          "skill1name": "Rainbow Cyclone",
          "skill1": "Deal 65% to the back column with a 80% chance to reduce SP by 25% for 3 turns",
          "skill1cd":  "100",
          "skill2img": "100106",
          "skill2name": "Body of Steel Muscle Explosion",
          "skill2": "Own column SP Damage Resistance +50% for 3 turns",
          "skill2cd":  "60",
          "autoname1": "Poison Resistance (B)",
          "auto1": "Increases Resistance against Poison status by 100%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg1": "POISONresist",
          "autoname2": "SP Damage Resistance (B)",
          "auto2": "Increases Resistance against SP Damage taken by 20%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoname3": "Seven Colored Youki",
          "auto3": "80% chance to Reduce an enemy's SP by 20%<br><hz>Duration:</hz> 2 turns <hz>Condition:</hz> when hit by a special <hz>Chance:</hz> 50%",
          "autoimg3": "SPdown",
          "autoname4": "Damage up (B)",
          "auto4": "Increases Damage given by 20%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg4": "DMGup",
          "autoname5": "Damage Reduction (B)",
          "auto5": "Reduces Damage taken by 20%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg5": "DMGresist",
          "lead": "Dex Type DEF +15%",
          "rank": "G"
},
      {
          "id": "10045",
          "name": "Genkai, Extreme Polished Warrior",
          "type": "yang",
          "class": "SP",
          "rare": "5",
          "power": "1058",
          "hp": "419",
          "atk": "104",
          "sp": "550",
          "def": "183",
          "spd": "115",
          "maxpower": "14986",
          "maxhp": "5984",
          "maxatk": "1484",
          "maxsp": "7856",
          "maxdef": "2612",
          "maxspd": "428",
          "skill1img": "100107",
          "skill1name": "Spirit Wave Orb",
          "skill1": "All allies SP +25% for 2 turns. Overall Damage +25% for 2 turns",
          "skill1cd":  "60",
          "skill2img": "100108",
          "skill2name": "Spirit Gun: Weapon",
          "skill2": "Deal 120% SP to target row",
          "skill2cd":  "100",
          "autoname1": "SP up (B)",
          "auto1": "Increases own SP by 25%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg1": "SPup",
          "autoname2": "Silence Resistance (B)",
          "auto2": "Increases Resistance against Silence status by 100%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg2": "SILENCEresist",
          "autoname3": "Skilled Special Move",
          "auto3": "Increases all allies's SP by 50%<br><hz>Duration:</hz> 2 turns <hz>Condition:</hz> upon death <hz>Chance:</hz> 100%",
          "autoname4": "Damage up (B)",
          "auto4": "Increases Damage given by 20%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg4": "DMGup",
          "autoname5": "Damage Reduction (B)",
          "auto5": "Reduces Damage taken by 20%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg5": "DMGresist",
          "lead": "Yang Type SP +15%",
          "rank": "G"
      },
      {
          "id": "10046",
          "name": "Yusuke Urameshi, Spirit's Successor",
          "type": "heart",
          "class": "SP",
          "rare": "5",
          "power": "1055",
          "hp": "419",
          "atk": "104",
          "sp": "549",
          "def": "183",
          "spd": "95",
          "maxpower": "14959",
          "maxhp": "5984",
          "maxatk": "1484",
          "maxsp": "7836",
          "maxdef": "2612",
          "maxspd": "352",
          "skill1img": "100109",
          "skill1name": "Spirit Gun: Light",
          "skill1": "Deal 75% SP to all enemy",
          "skill1cd":  "100",
          "skill2img": "100110",
          "skill2name": "Spirit Wave",
          "skill2": "Deal 165% SP to one enemy. Deal more damage when own HP is lower. (Maximum +225%)",
          "skill2cd":  "100",
          "autoname1": "Burn Resistance (B)",
          "auto1": "Increases Resistance against Burn status by 100%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg1": "BURNresist",
          "autoname2": "SP up (B)",
          "auto2": "Increases own SP by 25%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg2": "SPup",
          "autoname3": "Reikou's Successor",
          "auto3": "Increases own Heart Damage by 50%<br><hz>Duration:</hz> 2 turns <hz>Condition:</hz> when HP goes under 30% <hz>Chance:</hz> 100%",
          "autoimg3": "HEARTdmg",
          "autoname4": "Damage up (B)",
          "auto4": "Increases Damage given by 20%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg4": "DMGup",
          "autoname5": "Damage Reduction (B)",
          "auto5": "Reduces Damage taken by 20%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg5": "DMGresist",
          "lead": "Heart Type SP +15%",
          "rank": "G"
      },
      {
          "id": "10047",
          "name": "Kazuma Kuwabara, Flower Fantasy",
          "type": "yang",
          "class": "ATK",
          "rare": "5",
          "power": "1042",
          "hp": "415",
          "atk": "544",
          "sp": "103",
          "def": "181",
          "spd": "68",
          "maxpower": "14803",
          "maxhp": "5924",
          "maxatk": "7764",
          "maxsp": "2580",
          "maxdef": "1472",
          "maxspd": "252",
          "skill1img": "100111",
          "skill1name": "Spirit Flyswatter",
          "skill1": "Deal 85% ATK to front column with a 40% Chance to Stun for 1 turn",
          "skill1cd":  "110",
          "skill2img": "100112",
          "skill2name": "Spirit Sword Shards",
          "skill2": "Deal 180% ATK to one enemy",
          "skill2cd":  "100",
          "autoname1": "ATK up (B)",
          "auto1": "Increases own ATK by 25%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg1": "ATKup",
          "autoname2": "Stun Resistance (B)",
          "auto2": "Increases Resistance against Stun status by 100%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg2": "STUNresist",
          "autoname3": "A Man's Great Entrance",
          "auto3": "Casts Critical Effect on self<br><hz>Duration:</hz> 1 turn <hz>Condition:</hz> after a strengthening effect <hz>Chance:</hz> 30%",
          "autoimg3": "CRITeffect",
          "autoname4": "Damage up (B)",
          "auto4": "Increases Damage given by 20%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg4": "DMGup",
          "autoname5": "Damage Reduction (B)",
          "auto5": "Reduces Damage taken by 20%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg5": "DMGresist",
          "lead": "Yang Type ATK +15%",
          "rank": "G"
      },
      {
          "id": "10048",
          "name": "Kurama, Dazzling",
          "type": "body",
          "class": "DEF",
          "rare": "5",
          "power": "1044",
          "hp": "571",
          "atk": "310",
          "sp": "103",
          "def": "337",
          "spd": "90",
          "maxpower": "14815",
          "maxhp": "8148",
          "maxatk": "4424",
          "maxsp": "1472",
          "maxdef": "4812",
          "maxspd": "336",
          "skill1img": "100113",
          "skill1name": "Rose Whip Thorn Wheel",
          "skill1": "All allies ATK Damage Resistance +36% for 2 turns. +36% DEF for 2 turns",
          "skill1cd":  "60",
          "skill2img": "100114",
          "skill2name": "Bloodsucking Plant",
          "skill2": "Deal 188% ATK to one enemy with a 90% chance to inflict 10% Poison for 2 turns",
          "skill2cd":  "98",
          "autoname1": "ATK Damage Resistance (B)",
          "auto1": "Increases Resistance against ATK Damage taken by 25%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg1": "ATKDMGresist",
          "autoname2": "Poison Resistance (B)",
          "auto2": "Increases Resistance against Poison status by 100%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg2": "POISONresist",
          "autoname3": "Indomitable Will",
          "auto3": "Heals 50% HP<br><hz>Duration:</hz> instant <hz>Condition:</hz> when HP goes under 50% <hz>Chance:</hz> 100%/1 time",
          "autoimg3": "HEAL",
          "autoname4": "Damage up (B)",
          "auto4": "Increases Damage given by 20%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg4": "DMGup",
          "autoname5": "Damage Reduction (B)",
          "auto5": "Reduces Damage taken by 20%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg5": "DMGresist",
          "lead": "Body Type DEF +15%",
          "rank": "G"
      },
      {
          "id": "10050",
          "name": "Hiei, Single Stroke",
          "type": "dex",
          "class": "SP",
          "rare": "5",
          "power": "1053",
          "hp": "414",
          "atk": "103",
          "sp": "545",
          "def": "181",
          "spd": "170",
          "maxpower": "14885",
          "maxhp": "5912",
          "maxatk": "1472",
          "maxsp": "7784",
          "maxdef": "2580",
          "maxspd": "632",
          "skill1img": "100117",
          "skill1name": "Dragon of Darkness Flame",
          "skill1": "Deal 255% SP to target row. 90% chance to inflict 10% Burn for 2 turns. Silence self for 2 turns",
          "skill1cd":  "118",
          "skill2img": "100118",
          "skill2name": "Sword of Darkness Flames",
          "skill2": "Deal 270% SP to one enemy",
          "skill2cd":  "100",
          "autoname1": "Advantage Damage up (B)",
          "auto1": "Increases Damage against Advantage type by 25%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg1": "ADVDMGup",
          "autoname2": "Burn Resistance (B)",
          "auto2": "Increases Resistance against Burn status by 100%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg2": "BURNresist",
          "autoname3": "Black Tyranny",
          "auto3": "Increases own SP by 50%<br><hz>Duration:</hz> 2 turns <hz>Condition:</hz> at the start of the WAVE <hz>Chance:</hz> 100%",
          "autoimg3": "SPup",
          "autoname4": "Damage up (B)",
          "auto4": "Increases Damage given by 20%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg4": "DMGup",
          "autoname5": "Damage Reduction (B)",
          "auto5": "Reduces Damage taken by 20%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg5": "DMGresist",
          "lead": "Dex Type SP +15%",
          "rank": "G"
},
      {
          "id": "10051",
          "name": "Karasu, Beautiful Dark Evil",
          "type": "yin",
          "class": "ATK",
          "rare": "5",
          "power": "1049",
          "hp": "415",
          "atk": "544",
          "sp": "103",
          "def": "181",
          "spd": "141",
          "maxpower": "14830",
          "maxhp": "5924",
          "maxatk": "7764",
          "maxsp": "1472",
          "maxdef": "2580",
          "maxspd": "524",
          "skill1img": "100119",
          "skill1name": "Trace Eyes",
          "skill1": "Deal 125% ATK to one enemy with a 90% chance to inflict 10% Burn",
          "skill1cd":  "110",
          "skill2img": "100120",
          "skill2name": "Time Bomb",
          "skill2": "Deal 85% ATK to front column with a 25% chance to lower DEF for 3 turns",
          "skill2cd":  "100",
          "autoname1": "ATK up (B)",
          "auto1": "Increases own ATK by 25%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg1": "ATKup",
          "autoname2": "Freeze Resistance (B)",
          "auto2": "Increases Resistance against Freeze status by 100%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg2": "FREEZEresist",
          "autoname3": "Invisible Threat",
          "auto3": "80% chance to reduce enemy's DEF by 20%<br><hz>Duration:</hz> 2 turns <hz>Condition:</hz> after a strengthening effect <hz>Chance:</hz> 50%",
          "autoimg3": "DEFdown",
          "autoname4": "Damage up (B)",
          "auto4": "Increases Damage given by 20%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg4": "DMGup",
          "autoname5": "Damage Reduction (B)",
          "auto5": "Reduces Damage taken by 20%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg5": "DMGresist",
          "lead": "Yin Type ATK +15%",
          "rank": "G"
      }, 
      {
          "id": "10052",
          "name": "Bui, Large Axe and Heavy Armor",
          "type": "dex",
          "class": "ATK",
          "rare": "5",
          "power": "1046",
          "hp": "518",
          "atk": "415",
          "sp": "103",
          "def": "259",
          "spd": "106",
          "maxpower": "14827",
          "maxhp": "7392",
          "maxatk": "5924",
          "maxsp": "1472",
          "maxdef": "3696",
          "maxspd": "394",
          "skill1img": "100123",
          "skill1name": "Stone Throw",
          "skill1": "Deal 125% ATK to one enemy with a 70% chance to Stun for 1 turn",
          "skill1cd":  "110",
          "skill2img": "100124",
          "skill2name": "Tomahawk Ax",
          "skill2": "Deal 85% ATK to target row with a 80% chance to reduce ATK Damage Resistance by 25% for 3 turns",
          "skill2cd":  "100",
          "autoname1": "ATK up (B)",
          "auto1": "Increases own ATK by 25%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg1": "ATKup",
          "autoname2": "Blind Resistance (B)",
          "auto2": "Increases Resistance against Blind status by 100%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg2": "BLINDresist",
          "autoname3": "Sealed Fighting Spirit",
          "auto3": "80% chance to reduce enemy's ATK damage resistance by 20%<br><hz>Duration:</hz> 2 turns <hz>Condition:</hz> after a strengthening effect <hz>Chance:</hz> 50%",
          "autoimg3": "ATKDMGresistdown",
          "autoname4": "Damage up (B)",
          "auto4": "Increases Damage given by 20%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg4": "DMGup",
          "autoname5": "Damage Reduction (B)",
          "auto5": "Reduces Damage taken by 20%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg5": "DMGresist",
          "lead": "Dex Type ATK +15%",
          "rank": "G"
      },
      {
          "id": "10053",
          "name": "Elder Toguro, Brutal Sweep",
          "type": "yang",
          "class": "SP",
          "rare": "5",
          "power": "1058",
          "hp": "524",
          "atk": "105",
          "sp": "420",
          "def": "261",
          "spd": "100",
          "maxpower": "14999",
          "maxhp": "7484",
          "maxatk": "1496",
          "maxsp": "5996",
          "maxdef": "3728",
          "maxspd": "372",
          "skill1img": "100127",
          "skill1name": "Mimicry",
          "skill1": "Own column +57% Yang Damage. +20% HP regen for 3 turns",
          "skill1cd":  "58",
          "skill2img": "100128",
          "skill2name": "Weaponized Body",
          "skill2": "Deal +75% SP to all enemies",
          "skill2cd":  "100",
          "autoname1": "SP up (B)",
          "auto1": "Increases own SP by 25%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg1": "SPup",
          "autoname2": "Stun Resistance (B)",
          "auto2": "Increases Resistance against Stun status by 100%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg2": "STUNresist",
          "autoname3": "Immortal Body",
          "auto3": "Heals 15% HP<br><hz>Duration:</hz> instant <hz>Condition:</hz> upon death <hz>Chance:</hz> 100%/2 times",
          "autoimg3": "REVIVE",
          "autoname4": "Damage up (B)",
          "auto4": "Increases Damage given by 20%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg4": "DMGup",
          "autoname5": "Damage Reduction (B)",
          "auto5": "Reduces Damage taken by 20%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg5": "DMGresist",
          "lead": "Yang Type SP +15%",
          "rank": "G"
      },
      {
          "id": "10054",
          "name": "Younger Toguro, Super Powered Butcher",
          "type": "body",
          "class": "ATK",
          "rare": "5",
          "power": "1053",
          "hp": "524",
          "atk": "419",
          "sp": "104",
          "def": "261",
          "spd": "74",
          "maxpower": "14965",
          "maxhp": "7484",
          "maxatk": "5984",
          "maxsp": "1484",
          "maxdef": "3728",
          "maxspd": "276",
          "skill1img": "100129",
          "skill1name": "Super Powered Blow",
          "skill1": "Deal 110% ATK to one enemy. Deal more damage when own HP is higher (+100%)",
          "skill1cd":  "110",
          "skill2img": "100130",
          "skill2name": "Acidity Atmosphere",
          "skill2": "40% chance to inflict 10% Burn to front column for 2 turns. 80% chance to reduce ATK damage Resistance by 25% for 3 turns",
          "skill2cd":  "70",
          "autoname1": "Critical up (B)",
          "auto1": "Increases Critical Rate by 20%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg1": "CRITup",
          "autoname2": "Stun Resistance (B)",
          "auto2": "Increases Resistance against Stun status by 100%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg2": "STUNresist",
          "autoname3": "Mortality's Immense Strength",
          "auto3": "Increases own ATK by 30%<br><hz>Duration:</hz> 2 turns <hz>Condition:</hz> after using a special <hz>Chance:</hz> 30%",
          "autoimg3": "ATKup",
          "autoname4": "Damage up (B)",
          "auto4": "Increases Damage given by 20%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg4": "DMGup",
          "autoname5": "Damage Reduction (B)",
          "auto5": "Reduces Damage taken by 20%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg5": "DMGresist",
          "lead": "Body Type ATK +15%",
          "rank": "G"
      },
      {
          "id": "10055",
          "name": "Younger Toguro, Leaking Evil",
          "type": "yin",
          "class": "ATK",
          "rare": "5",
          "power": "1061",
          "hp": "422",
          "atk": "554",
          "sp": "105",
          "def": "184",
          "spd": "72",
          "maxpower": "15066",
          "maxhp": "6024",
          "maxatk": "7908",
          "maxsp": "1496",
          "maxdef": "2624",
          "maxspd": "268",
          "skill1img": "100131",
          "skill1name": "Shidan",
          "skill1": "Deal 180% ATK to target row.",
          "skill1cd":  "100",
          "skill2img": "100132",
          "skill2name": "Threat of a Superior Class",
          "skill2": "Deal 90% ATK to all enemies with a 70% chance to reduce enemy's ATK Damage Resistance by 29% for 2 turns. Own ATK -50% for 2 turns",
          "skill2cd":  "120",
          "autoname1": "Advantage Damage up (B)",
          "auto1": "Increases Damage against Advantage type by 25%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg1": "ADVDMGup",
          "autoname2": "Poison Resistance (B)",
          "auto2": "Increases Resistance against Poison status by 100%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg2": "POISONresist",
          "autoname3": "100% Wave",
          "auto3": "Increases own ATK by 100%<br><hz>Duration:</hz> 1 turn <hz>Condition:</hz> after defeating an enemy <hz>Chance:</hz> 50%",
          "autoimg3": "ATKup",
          "autoname4": "Damage up (B)",
          "auto4": "Increases Damage given by 20%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg4": "DMGup",
          "autoname5": "Damage Reduction (B)",
          "auto5": "Reduces Damage taken by 20%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg5": "DMGresist",
          "lead": "Yang Type SP +15%",
          "rank": "G"
},
      {
          "id": "10127",
          "name": "Chu, Drunken Style Fighter",
          "type": "yin",
          "class": "SP",
          "rare": "5",
          "power": "1041",
          "hp": "410",
          "atk": "102",
          "sp": "540",
          "def": "179",
          "spd": "150",
          "maxpower": "",
          "maxhp": "",
          "maxatk": "",
          "maxsp": "",
          "maxdef": "",
          "maxspd": "",
          "skill1img": "100245",
          "skill1name": "Drink Enhancement",
          "skill1": "Own row SP +40% for 3 turns. +40% advantage damage for 3 turns",
          "skill1cd":  "60",
          "skill2img": "100246",
          "skill2name": "Ogre Boulder",
          "skill2": "Deal 120% SP to front column",
          "skill2cd":  "100",
          "autoname1": "Stun Resistance (B)",
          "auto1": "Increases Resistance against Stun status by 100%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg1": "STUNresist",
          "autoname2": "SP up (B)",
          "auto2": "Increases own SP by 25%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg2": "SPup",
          "autoname3": "Demon Alchemy",
          "auto3": "Increases Damage against Advantage type of ally by 20%<br><hz>Duration:</hz> 2 turns <hz>Condition:</hz> when ally kills an enemy <hz>Chance:</hz> 50%",
          "autoimg3": "ADVDMGup",
          "autoname4": "Damage up (B)",
          "auto4": "Increases Damage given by 20%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg4": "DMGup",
          "autoname5": "Damage Reduction (B)",
          "auto5": "Reduces Damage taken by 20%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg5": "DMGresist",
          "lead": "Yin Type SP +15%",
          "rank": "G"
}, 
            // -------------------------------------------------------------------------------- 
                                              // 4 STAR CARDS
            // -------------------------------------------------------------------------------- 
            
            {
          "id": "10060",
          "name": "Yusuke Urameshi, Shotgun Light Fist",
          "type": "yang",
          "class": "SP",
          "rare": "4",
          "power": "732",
          "hp": "363",
          "atk": "72",
          "sp": "289",
          "def": "181",
          "spd": "91",
          "maxpower": "",
          "maxhp": "",
          "maxatk": "",
          "maxsp": "",
          "maxdef": "",
          "maxspd": "",
          "skill1img": "100043",
          "skill1name": "Spirit Fist Barrier",
          "skill1": "Own column SP Damage Resistance +30% for 3 turns",
          "skill1cd":  "60",
          "skill2img": "100044",
          "skill2name": "Shotgun",
          "skill2": "Deal 110% SP to front column",
          "skill2cd":  "100",
          "autoname1": "Paralyze Resistance (B)",
          "auto1": "Increases Resistance against Paralyze Status by 100%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg1": "PARAresist",
          "autoname2": "SP up (M)",
          "auto2": "Increases own SP by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg2": "SPup",
          "autoname3": "",
          "auto3": "",
          "autoimg3": "",
          "autoname4": "Damage up (M)",
          "auto4": "Increases Damage given by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg4": "DMGup",
          "autoname5": "Damage Reduction (M)",
          "auto5": "Reduces Damage taken by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg5": "DMGresist",
          "lead": "Yang Type SP +10%",
          "rank": "G"
            },
            {
          "id": "10058",
          "name": "Kazuma Kuwabara, Double Extend Reiken",
          "type": "body",
          "class": "SP",
          "rare": "4",
          "power": "726",
          "hp": "361",
          "atk": "70",
          "sp": "287",
          "def": "80",
          "spd": "97",
          "maxpower": "",
          "maxhp": "",
          "maxatk": "",
          "maxsp": "",
          "maxdef": "",
          "maxspd": "",
          "skill1img": "100299",
          "skill1name": "Heaven Thrust Spiritual Sword",
          "skill1": "Deal 80% SP to target row. 70% chance to reduce SP Damage Resistance by 20% for 3 turns",
          "skill1cd":  "100",
          "skill2img": "100300",
          "skill2name": "Double Spiritual Sword",
          "skill2": "Deal 170% SP to one enemy",
          "skill2cd":  "100",
          "autoname1": "Stun Resistance (B)",
          "auto1": "Increases Resistance against Paralyze Status by 100%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg1": "STUNresist",
          "autoname2": "SP up (M)",
          "auto2": "Increases own SP by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg2": "SPup",
          "autoname3": "",
          "auto3": "",
          "autoimg3": "",
          "autoname4": "Damage up (M)",
          "auto4": "Increases Damage given by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg4": "DMGup",
          "autoname5": "Damage Reduction (M)",
          "auto5": "Reduces Damage taken by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg5": "DMGresist",
          "lead": "Body Type SP +10%",
          "rank": "G"
      },
            {
          "id": "10005",
          "name": "Hiei, Jagan Amplification",
          "type": "yin",
          "class": "ATK",
          "rare": "4",
          "power": "722",
          "hp": "285",
          "atk": "374",
          "sp": "70",
          "def": "124",
          "spd": "120",
          "maxpower": "",
          "maxhp": "",
          "maxatk": "",
          "maxsp": "",
          "maxdef": "",
          "maxspd": "",
          "skill1img": "100009",
          "skill1name": "Invisible Instant Attack",
          "skill1": "Deal 204% ATK to one enemy",
          "skill1cd":  "100",
          "skill2img": "100010",
          "skill2name": "Biding Spell",
          "skill2": "30% chance to Paralyze the back column for 1 turn",
          "skill2cd":  "80",
          "autoname1": "Poison Resistance (B)",
          "auto1": "Increases Resistance against Poison Status by 100%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg1": "POISONresist",
          "autoname2": "ATK up (M)",
          "auto2": "Increases own ATK by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg2": "ATKup",
          "autoname3": "",
          "auto3": "",
          "autoimg3": "",
          "autoname4": "Damage up (M)",
          "auto4": "Increases Damage given by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg4": "DMGup",
          "autoname5": "Damage Reduction (M)",
          "auto5": "Reduces Damage taken by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg5": "DMGresist",
          "lead": "Yin Type ATK +10%",
          "rank": "G"
      },
            {
          "id": "10063",
          "name": "Hiei, Jet Black Swordsman",
          "type": "heart",
          "class": "ATK",
          "rare": "4",
          "power": "744",
          "hp": "363",
          "atk": "291",
          "sp": "72",
          "def": "181",
          "spd": "187",
          "maxpower": "",
          "maxhp": "",
          "maxatk": "",
          "maxsp": "",
          "maxdef": "",
          "maxspd": "",
          "skill1img": "100293",
          "skill1name": "A Moment's Slicing Outburst",
          "skill1": "Deal 110% ATK to enemy front row",
          "skill1cd":  "100",
          "skill2img": "100294",
          "skill2name": "Blink of a Shadowless Move",
          "skill2": "Own row ATK +20% for 3 turns. Blocks damage taken 1 time",
          "skill2cd":  "60",
          "autoname1": "Silence Resistance (B)",
          "auto1": "Increases Resistance against Silence Status by 100%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg1": "SILENCEresist",
          "autoname2": "ATK up (M)",
          "auto2": "Increases own ATK by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg2": "ATKup",
          "autoname3": "",
          "auto3": "",
          "autoimg3": "",
          "autoname4": "Damage up (M)",
          "auto4": "Increases Damage given by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg4": "DMGup",
          "autoname5": "Damage Reduction (M)",
          "auto5": "Reduces Damage taken by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg5": "DMGresist",
          "lead": "Heart Type ATK +10%",
          "rank": "G"
      },
            {
          "id": "10064",
          "name": "Genkai, Soaring Light Purification",
          "type": "body",
          "class": "SP",
          "rare": "4",
          "power": "748",
          "hp": "294",
          "atk": "72",
          "sp": "386",
          "def": "128",
          "spd": "159",
          "maxpower": "",
          "maxhp": "",
          "maxatk": "",
          "maxsp": "",
          "maxdef": "",
          "maxspd": "",
          "skill1img": "100075",
          "skill1name": "Spiritual Bullet Purification",
          "skill1": "Deal 45% SP to enemy team",
          "skill1cd":  "100",
          "skill2img": "100076",
          "skill2name": "Light Cleasing",
          "skill2": "Deal SP 120% to enemy team. Reduce strengthening effects duration by 1 turn",
          "skill2cd":  "110",
          "autoname1": "Silence Resistance (B)",
          "auto1": "Increases Resistance against Silence Status by 100%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg1": "SILENCEresist",
          "autoname2": "SP up (M)",
          "auto2": "Increases own SP by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg2": "SPup",
          "autoname3": "",
          "auto3": "",
          "autoimg3": "",
          "autoname4": "Damage up (M)",
          "auto4": "Increases Damage given by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg4": "DMGup",
          "autoname5": "Damage Reduction (M)",
          "auto5": "Reduces Damage taken by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg5": "DMGresist",
          "lead": "Body Type SP +10%",
          "rank": "G"
      },
            {
          "id": "10057",
          "name": "Randou, Hundred Techniques",
          "type": "yin",
          "class": "SP",
          "rare": "4",
          "power": "607",
          "hp": "241",
          "atk": "59",
          "sp": "315",
          "def": "104",
          "spd": "86",
          "maxpower": "4181",
          "maxhp": "1671",
          "maxatk": "411",
          "maxsp": "2184",
          "maxdef": "726",
          "maxspd": "252",
          "skill1img": "100031",
          "skill1name": "Spell Technique",
          "skill1": "80% Chance to reduce target's DEF by 30% for 2 turns. If target is a SP type, 80% chance to reduce yin attribute damage by 40% for 3 turns",
          "skill1cd":  "60",
          "skill2img": "100032",
          "skill2name": "Reigan Imitation",
          "skill2": "Deal 110% SP to enemy row",
          "skill2cd":  "100",
          "autoname1": "Yin Damage up (M)",
          "auto1": "Increases own Yin damage by 20%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg1": "YINDMGup",
          "autoname2": "Stun Resistance (B)",
          "auto2": "Increases Resistance against Stun Status by 100%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg2": "STUNresist",
          "autoname3": "",
          "auto3": "",
          "autoimg3": "",
          "autoname4": "Damage up (M)",
          "auto4": "Increases Damage given by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg4": "DMGup",
          "autoname5": "Damage Reduction (M)",
          "auto5": "Reduces Damage taken by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg5": "DMGresist",
          "lead": "Yin Type SP +10%",
          "rank": "G"
      },
            {
          "id": "10019",
          "name": "Suzaku, Great Thunder Summoning",
          "type": "yin",
          "class": "SP",
          "rare": "4",
          "power": "737",
          "hp": "291",
          "atk": "72",
          "sp": "383",
          "def": "127",
          "spd": "95",
          "maxpower": "",
          "maxhp": "",
          "maxatk": "",
          "maxsp": "",
          "maxdef": "",
          "maxspd": "",
          "skill1img": "100039",
          "skill1name": "Storm of Torment",
          "skill1": "Deal 120% SP to an enemy with 40% chance to paralyze them for 1 turn",
          "skill1cd":  "110",
          "skill2img": "100040",
          "skill2name": "Prism Storm of Torment",
          "skill2": "Deal 80% SP to enemy back row",
          "skill2cd":  "100",
          "autoname1": "Paralyze Resistance (B)",
          "auto1": "Increases Resistance against Paralyze Status by 100%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg1": "PARAresist",
          "autoname2": "SP up (M)",
          "auto2": "Increases own SP by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg2": "SPup",
          "autoname3": "",
          "auto3": "",
          "autoimg3": "",
          "autoname4": "Damage up (M)",
          "auto4": "Increases Damage given by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg4": "DMGup",
          "autoname5": "Damage Reduction (M)",
          "auto5": "Reduces Damage taken by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg5": "DMGresist",
          "lead": "Yin Type SP +10%",
          "rank": "G"
      },
            {
          "id": "10025",
          "name": "Zeru, Flame User",
          "type": "heart",
          "class": "SP",
          "rare": "4",
          "power": "732",
          "hp": "326",
          "atk": "72",
          "sp": "344",
          "def": "144",
          "spd": "94",
          "maxpower": "",
          "maxhp": "",
          "maxatk": "",
          "maxsp": "",
          "maxdef": "",
          "maxspd": "",
          "skill1img": "100059",
          "skill1name": "Dark Fire Shot",
          "skill1": "Deal 120% SP damage to single target. 55% chance to inflict 10% Burn for 2 turns",
          "skill1cd":  "110",
          "skill2img": "100060",
          "skill2name": "Dark Fire Absorption",
          "skill2": "Own row +35% of heart damage for 3 turns",
          "skill2cd":  "100",
          "autoname1": "Burn Resistance (B)",
          "auto1": "Increases Resistance against Burn Status by 100%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg1": "BURNresist",
          "autoname2": "SP up (M)",
          "auto2": "Increases own SP by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg2": "SPup",
          "autoname3": "",
          "auto3": "",
          "autoimg3": "",
          "autoname4": "Damage up (M)",
          "auto4": "Increases Damage given by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg4": "DMGup",
          "autoname5": "Damage Reduction (M)",
          "auto5": "Reduces Damage taken by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg5": "DMGresist",
          "lead": "Heart Type SP +10%",
          "rank": "G"
      },
            {
          "id": "10026",
          "name": "Chu, Demon Alchemist",
          "type": "body",
          "class": "DEF",
          "rare": "4",
          "power": "749",
          "hp": "403",
          "atk": "72",
          "sp": "220",
          "def": "238",
          "spd": "178",
          "maxpower": "",
          "maxhp": "",
          "maxatk": "",
          "maxsp": "",
          "maxdef": "",
          "maxspd": "",
          "skill1img": "100061",
          "skill1name": "Ogre Killer",
          "skill1": "Deal 110% SP damage to enemy row",
          "skill1cd":  "100",
          "skill2img": "100062",
          "skill2name": "Drunken Alchemy Style",
          "skill2": "Cast Provoke Effect on self for 2 turns. Block damage taken 2 times",
          "skill2cd":  "60",
          "autoname1": "Blind Resistance (B)",
          "auto1": "Increases Resistance against Blind Status by 100%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg1": "BLINDresist",
          "autoname2": "DEF up (M)",
          "auto2": "Increases own DEF by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg2": "DEFup",
          "autoname3": "",
          "auto3": "",
          "autoimg3": "",
          "autoname4": "Damage up (M)",
          "auto4": "Increases Damage given by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg4": "DMGup",
          "autoname5": "Damage Reduction (M)",
          "auto5": "Reduces Damage taken by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg5": "DMGresist",
          "lead": "Body Type DEF +10%",
          "rank": "G"
      },
            {
          "id": "10034",
          "name": "Gatasubal, Cyborg Demon",
          "type": "yin",
          "class": "DEF",
          "rare": "4",
          "power": "734",
          "hp": "400",
          "atk": "217",
          "sp": "72",
          "def": "236",
          "spd": "91",
          "maxpower": "",
          "maxhp": "",
          "maxatk": "",
          "maxsp": "",
          "maxdef": "",
          "maxspd": "",
          "skill1img": "100081",
          "skill1name": "Enemy Recognition",
          "skill1": "Own column guard percentage +20% for 3 turns. Increases own ATK damage resistance by 20% for 3 turns",
          "skill1cd":  "60",
          "skill2img": "100082",
          "skill2name": "Pursuing Long Arms Shot",
          "skill2": "Deal 80% ATK to enemy back row",
          "skill2cd":  "100",
          "autoname1": "Stun Resistance (B)",
          "auto1": "Increases Resistance against Stun Status by 100%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg1": "STUNresist",
          "autoname2": "DEF up (M)",
          "auto2": "Increases own DEF by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg2": "DEFup",
          "autoname3": "",
          "auto3": "",
          "autoimg3": "",
          "autoname4": "Damage up (M)",
          "auto4": "Increases Damage given by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg4": "DMGup",
          "autoname5": "Damage Reduction (M)",
          "auto5": "Reduces Damage taken by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg5": "DMGresist",
          "lead": "Yin Type DEF +10%",
          "rank": "G"
      },
            {
          "id": "10036",
          "name": "Gama, Makeup User",
          "type": "dex",
          "class": "DEF",
          "rare": "4",
          "power": "733",
          "hp": "400",
          "atk": "72",
          "sp": "217",
          "def": "236",
          "spd": "87",
          "maxpower": "",
          "maxhp": "",
          "maxatk": "",
          "maxsp": "",
          "maxdef": "",
          "maxspd": "",
          "skill1img": "100085",
          "skill1name": "Body Makeup",
          "skill1": "Own column SP damage resistance +35% for 3 turns",
          "skill1cd":  "60",
          "skill2img": "100086",
          "skill2name": "Makeup of Chains",
          "skill2": "80% chance of reducing target's SP by 30% for 2 turns. 40% chance to paralyze the target for 1 turn",
          "skill2cd":  "70",
          "autoname1": "Silence Resistance (B)",
          "auto1": "Increases Resistance against Silence Status by 100%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg1": "SILENCEresist",
          "autoname2": "SP damage resistance (M)",
          "auto2": "Increases Resistance against SP damage taken by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg2": "SPDMGresist",
          "autoname3": "",
          "auto3": "",
          "autoimg3": "",
          "autoname4": "Damage up (M)",
          "auto4": "Increases Damage given by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg4": "DMGup",
          "autoname5": "Damage Reduction (M)",
          "auto5": "Reduces Damage taken by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg5": "DMGresist",
          "lead": "Dex Type DEF +10%",
          "rank": "G"
      },
            {
          "id": "10039",
          "name": "Rishou, Explosive Waves",
          "type": "heart",
          "class": "DEF",
          "rare": "4",
          "power": "734",
          "hp": "400",
          "atk": "217",
          "sp": "72",
          "def": "236",
          "spd": "91",
          "maxpower": "",
          "maxhp": "",
          "maxatk": "",
          "maxsp": "",
          "maxdef": "",
          "maxspd": "",
          "skill1img": "100091",
          "skill1name": "Meteor Attack",
          "skill1": "Deal 170% ATK to target",
          "skill1cd":  "100",
          "skill2img": "100092",
          "skill2name": "Armor of Clay",
          "skill2": "Own column ATK damage resistance +35% for 3 turns",
          "skill2cd":  "60",
          "autoname1": "Stun Resistance (B)",
          "auto1": "Increases Resistance against Stun Status by 100%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg1": "STUNresist",
          "autoname2": "ATK damage resistance (M)",
          "auto2": "Increases Resistance against ATK damage taken by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg2": "ATKDMGresist",
          "autoname3": "",
          "auto3": "",
          "autoimg3": "",
          "autoname4": "Damage up (M)",
          "auto4": "Increases Damage given by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg4": "DMGup",
          "autoname5": "Damage Reduction (M)",
          "auto5": "Reduces Damage taken by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg5": "DMGresist",
          "lead": "Heart Type DEF +10%",
          "rank": "G"
      },
            {
          "id": "10042",
          "name": "Ura Urashima, Trickster Youkai",
          "type": "yang",
          "class": "ATK",
          "rare": "4",
          "power": "730",
          "hp": "326",
          "atk": "346",
          "sp": "72",
          "def": "144",
          "spd": "59",
          "maxpower": "",
          "maxhp": "",
          "maxatk": "",
          "maxsp": "",
          "maxdef": "",
          "maxspd": "",
          "skill1img": "100101",
          "skill1name": "Whip Storm Dance",
          "skill1": "Deal 170% ATK to target",
          "skill1cd":  "100",
          "skill2img": "100102",
          "skill2name": "String Barrier",
          "skill2": "70% chance to reduce all enemies ATK damage resistance by 20% for 3 turns",
          "skill2cd":  "60",
          "autoname1": "Stun Resistance (B)",
          "auto1": "Increases Resistance against Stun Status by 100%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg1": "STUNresist",
          "autoname2": "ATK damage resistance (M)",
          "auto2": "Increases Resistance against ATK damage taken by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg2": "ATKDMGresist",
          "autoname3": "",
          "auto3": "",
          "autoimg3": "",
          "autoname4": "Damage up (M)",
          "auto4": "Increases Damage given by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg4": "DMGup",
          "autoname5": "Damage Reduction (M)",
          "auto5": "Reduces Damage taken by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg5": "DMGresist",
          "lead": "Heart Type DEF +10%",
          "rank": "G"
      },
            {
          "id": "10062",
          "name": "Toguro, Destructive Pressure",
          "type": "dex",
          "class": "ATK",
          "rare": "4",
          "power": "502",
          "hp": "223",
          "atk": "236",
          "sp": "49",
          "def": "99",
          "spd": "73",
          "maxpower": "5952",
          "maxhp": "2667",
          "maxatk": "2825",
          "maxsp": "585",
          "maxdef": "1183",
          "maxspd": "262",
          "skill1img": "100053",
          "skill1name": "Explosive Power Charge",
          "skill1": "Deal 170% ATK to target",
          "skill1cd":  "100",
          "skill2img": "100054",
          "skill2name": "Rakshasa Back Flash",
          "skill2": "70% chance to reduce all enemies ATK damage resistance by 20% for 3 turns",
          "skill2cd":  "70",
          "autoname1": "DEX damage up (M)",
          "auto1": "Increases DEX damage by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg1": "DEXdmg",
          "autoname2": "Poison Resistance (B)",
          "auto2": "Increases Resistance against Poison Status by 100%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg2": "POISONresist",
          "autoname3": "",
          "auto3": "",
          "autoimg3": "",
          "autoname4": "Damage up (M)",
          "auto4": "Increases Damage given by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg4": "DMGup",
          "autoname5": "Damage Reduction (M)",
          "auto5": "Reduces Damage taken by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg5": "DMGresist",
          "lead": "Dex Type ATK +10%",
          "rank": "G"
      },
            {
          "id": "10065",
          "name": "Kuro Momotaro, Armor of the Wolf",
          "type": "body",
          "class": "ATK",
          "rare": "4",
          "power": "743",
          "hp": "368",
          "atk": "292",
          "sp": "72",
          "def": "183",
          "spd": "120",
          "maxpower": "",
          "maxhp": "",
          "maxatk": "",
          "maxsp": "",
          "maxdef": "",
          "maxspd": "",
          "skill1img": "100099",
          "skill1name": "Wolf's Tearing Claw",
          "skill1": "Deal 120% ATK to target. 80% chance to reduce target's DEF by 30% for 2 turns",
          "skill1cd":  "100",
          "skill2img": "100100",
          "skill2name": "Beast Armor Number 3",
          "skill2": "All allies ATK +20% for 3 turns",
          "skill2cd":  "70",
          "autoname1": "Freeze Resistance (B)",
          "auto1": "Increases Resistance against Freeze Status by 100%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg1": "FREEZEresist",
          "autoname2": "ATK up (M)",
          "auto2": "Increases own ATK by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg2": "ATKup",
          "autoname3": "",
          "auto3": "",
          "autoimg3": "",
          "autoname4": "Damage up (M)",
          "auto4": "Increases Damage given by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg4": "DMGup",
          "autoname5": "Damage Reduction (M)",
          "auto5": "Reduces Damage taken by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg5": "DMGresist",
          "lead": "Body Type ATK +10%",
          "rank": "G"
      },
            {
          "id": "10074",
          "name": "Asato Kido, Shadow",
          "type": "dex",
          "class": "SP",
          "rare": "4",
          "power": "723",
          "hp": "359",
          "atk": "70",
          "sp": "288",
          "def": "180",
          "spd": "62",
          "maxpower": "",
          "maxhp": "",
          "maxatk": "",
          "maxsp": "",
          "maxdef": "",
          "maxspd": "",
          "skill1img": "100135",
          "skill1name": "Shadow",
          "skill1": "40% Chance to paralyze the target for 1 turn. 80% chance to reduce target's DEF by 30% for 2 turns",
          "skill1cd":  "70",
          "skill2img": "100136",
          "skill2name": "Shadow Binded Hitting",
          "skill2": "Deal 170% SP to target",
          "skill2cd":  "100",
          "autoname1": "Paralyze Resistance (B)",
          "auto1": "Increases Resistance against Paralyze Status by 100%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg1": "PARAresist",
          "autoname2": "SP up (M)",
          "auto2": "Increases own SP by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg2": "SPup",
          "autoname3": "",
          "auto3": "",
          "autoimg3": "",
          "autoname4": "Damage up (M)",
          "auto4": "Increases Damage given by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg4": "DMGup",
          "autoname5": "Damage Reduction (M)",
          "auto5": "Reduces Damage taken by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg5": "DMGresist",
          "lead": "Body Type ATK +10%",
          "rank": "G"
      },
            {
          "id": "10075",
          "name": "Yuu Kaitou, Taboo",
          "type": "yin",
          "class": "DEF",
          "rare": "4",
          "power": "719",
          "hp": "398",
          "atk": "70",
          "sp": "215",
          "def": "233",
          "spd": "29",
          "maxpower": "",
          "maxhp": "",
          "maxatk": "",
          "maxsp": "",
          "maxdef": "",
          "maxspd": "",
          "skill1img": "100137",
          "skill1name": "Taboo",
          "skill1": "80% chance to cast silence on target for 2 turns",
          "skill1cd":  "80",
          "skill2img": "100138",
          "skill2name": "Taboo of Speech",
          "skill2": "All allies +20% ATK damage resist for 3 turns",
          "skill2cd":  "60",
          "autoname1": "Silence Resistance (B)",
          "auto1": "Increases Resistance against Silence Status by 100%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg1": "SILENCEresist",
          "autoname2": "SP Damage Resist (M)",
          "auto2": "Increases resistance against SP damage taken by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg2": "SPDMGresist",
          "autoname3": "",
          "auto3": "",
          "autoimg3": "",
          "autoname4": "Damage up (M)",
          "auto4": "Increases Damage given by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg4": "DMGup",
          "autoname5": "Damage Reduction (M)",
          "auto5": "Reduces Damage taken by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg5": "DMGresist",
          "lead": "Yin Type DEF +10%",
          "rank": "G"
      },
            {
          "id": "10076",
          "name": "Mitsunari Yanagisawa, Copy",
          "type": "yang",
          "class": "ATK",
          "rare": "4",
          "power": "724",
          "hp": "361",
          "atk": "288",
          "sp": "70",
          "def": "180",
          "spd": "56",
          "maxpower": "",
          "maxhp": "",
          "maxatk": "",
          "maxsp": "",
          "maxdef": "",
          "maxspd": "",
          "skill1img": "100139",
          "skill1name": "Memory Copy",
          "skill1": "Copy the skill used by the last ally (if there's no skill used to copy, only attack)",
          "skill1cd":  "120",
          "skill2img": "100140",
          "skill2name": "Instant Copy",
          "skill2": "Copy an ally's skill (if there's no skill to copy, only attack)",
          "skill2cd":  "120",
          "autoname1": "Silence Resistance (B)",
          "auto1": "Increases Resistance against Silence Status by 100%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg1": "SILENCEresist",
          "autoname2": "ATK up (M)",
          "auto2": "Increases own ATK by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg2": "ATKup",
          "autoname3": "",
          "auto3": "",
          "autoimg3": "",
          "autoname4": "Damage up (M)",
          "auto4": "Increases Damage given by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg4": "DMGup",
          "autoname5": "Damage Reduction (M)",
          "auto5": "Reduces Damage taken by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg5": "DMGresist",
          "lead": "Yang Type ATK +10%",
          "rank": "G"
      },
            {
          "id": "10077",
          "name": "Minoru Kamiya, Doctor",
          "type": "dex",
          "class": "ATK",
          "rare": "4",
          "power": "746",
          "hp": "372",
          "atk": "296",
          "sp": "74",
          "def": "185",
          "spd": "58",
          "maxpower": "",
          "maxhp": "",
          "maxatk": "",
          "maxsp": "",
          "maxdef": "",
          "maxspd": "",
          "skill1img": "100141",
          "skill1name": "Psychic Scalpel",
          "skill1": "Deal 110% ATK to enemy row",
          "skill1cd":  "100",
          "skill2img": "100142",
          "skill2name": "Surgery",
          "skill2": "Own row +30% HP",
          "skill2cd":  "80",
          "autoname1": "Poison Resistance (B)",
          "auto1": "Increases Resistance against Poison Status by 100%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg1": "POISONresist",
          "autoname2": "ATK up (M)",
          "auto2": "Increases own ATK by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg2": "ATKup",
          "autoname3": "",
          "auto3": "",
          "autoimg3": "",
          "autoname4": "Damage up (M)",
          "auto4": "Increases Damage given by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg4": "DMGup",
          "autoname5": "Damage Reduction (M)",
          "auto5": "Reduces Damage taken by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg5": "DMGresist",
          "lead": "Dex Type ATK +10%",
          "rank": "G"
      },
            {
          "id": "10081",
          "name": "Tsukihito Amanuma, Gamemaster",
          "type": "yang",
          "class": "DEF",
          "rare": "4",
          "power": "719",
          "hp": "396",
          "atk": "70",
          "sp": "215",
          "def": "233",
          "spd": "32",
          "maxpower": "",
          "maxhp": "",
          "maxatk": "",
          "maxsp": "",
          "maxdef": "",
          "maxspd": "",
          "skill1img": "100149",
          "skill1name": "Slot Game",
          "skill1": "35% Chance to deal 10% burn to enemy row for 2 turns, 15% chance to freeze for 1 turn, 25% chance to silence for 1 turn and 25% chance to blind and miss 50% of attacks for 2 turns",
          "skill1cd":  "110",
          "skill2img": "100150",
          "skill2name": "Three Seven",
          "skill2": "Deal 100% SP to target with 70% chance to reduce 15% of ATK, SP and given damage for 2 turns",
          "skill2cd":  "120",
          "autoname1": "Poison Resistance (B)",
          "auto1": "Increases Resistance against Poison Status by 100%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg1": "POISONresist",
          "autoname2": "SP Damage Resist (M)",
          "auto2": "Increases Resistance against SP damage taken by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg2": "SPDMGresist",
          "autoname3": "",
          "auto3": "",
          "autoimg3": "",
          "autoname4": "Damage up (M)",
          "auto4": "Increases Damage given by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg4": "DMGup",
          "autoname5": "Damage Reduction (M)",
          "auto5": "Reduces Damage taken by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg5": "DMGresist",
          "lead": "Yang Type DEF +10%",
          "rank": "G"
      },
            {
          "id": "10082",
          "name": "Sadao Makihara, Gourmet",
          "type": "dex",
          "class": "DEF",
          "rare": "4",
          "power": "718",
          "hp": "396",
          "atk": "215",
          "sp": "70",
          "def": "233",
          "spd": "28",
          "maxpower": "",
          "maxhp": "",
          "maxatk": "",
          "maxsp": "",
          "maxdef": "",
          "maxspd": "",
          "skill1img": "100151",
          "skill1name": "Bare Handed Eating",
          "skill1": "Own HP +20% and DEF +30% for 2 turns",
          "skill1cd":  "60",
          "skill2img": "100152",
          "skill2name": "Piercing Occupation",
          "skill2": "Deal 170% ATK one enemy",
          "skill2cd":  "100",
          "autoname1": "Freeze Resistance (B)",
          "auto1": "Increases Resistance against Freeze Status by 100%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg1": "FREEZEresist",
          "autoname2": "DEF up (M)",
          "auto2": "Increases own DEF by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg2": "DEFup",
          "autoname3": "",
          "auto3": "",
          "autoimg3": "",
          "autoname4": "Damage up (M)",
          "auto4": "Increases Damage given by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg4": "DMGup",
          "autoname5": "Damage Reduction (M)",
          "auto5": "Reduces Damage taken by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg5": "DMGresist",
          "lead": "Dex Type DEF +10%",
          "rank": "G"
      },
            {
          "id": "18004",
          "name": "Shigeru Murota, Tapping",
          "type": "heart",
          "class": "ATK",
          "rare": "4",
          "power": "716",
          "hp": "356",
          "atk": "285",
          "sp": "70",
          "def": "178",
          "spd": "54",
          "maxpower": "",
          "maxhp": "",
          "maxatk": "",
          "maxsp": "",
          "maxdef": "",
          "maxspd": "",
          "skill1img": "100173",
          "skill1name": "Tapping",
          "skill1": "Own row +30% ATK for 3 turns. Blocks damage 1 time",
          "skill1cd":  "60",
          "skill2img": "100174",
          "skill2name": "Gazelle Punch",
          "skill2": "Deal 120% to target with 80% chance to reduce DEF by 30% for 2 turns",
          "skill2cd":  "100",
          "autoname1": "Poison Resistance (B)",
          "auto1": "Increases Resistance against Poison Status by 100%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg1": "POISONresist",
          "autoname2": "Stun Resistance (B)",
          "auto2": "Increases Resistance against Stun Status by 100%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg2": "STUNresist",
          "autoname3": "",
          "auto3": "",
          "autoimg3": "",
          "autoname4": "Damage up (M)",
          "auto4": "Increases Damage given by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg4": "DMGup",
          "autoname5": "Damage Reduction (M)",
          "auto5": "Reduces Damage taken by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg5": "DMGresist",
          "lead": "Heart Type ATK +10%",
          "rank": "G"
      },
            
             // -------------------------------------------------------------------------------- 
                                              // 3 STAR CARDS
            // -------------------------------------------------------------------------------- 
            
            {
          "id": "10001",
          "name": "Yusuke Urameshi, Sarayashiki School nº1",
          "type": "dex",
          "class": "SP",
          "rare": "3",
          "power": "388",
          "hp": "190",
          "atk": "38",
          "sp": "153",
          "def": "95",
          "spd": "74",
          "maxpower": "",
          "maxhp": "",
          "maxatk": "",
          "maxsp": "",
          "maxdef": "",
          "maxspd": "",
          "skill1img": "100001",
          "skill1name": "Delinquent Iron Fist",
          "skill1": "Deal 160% SP to one enemy",
          "skill1cd":  "100",
          "skill2img": "100002",
          "skill2name": "Spirit Gun",
          "skill2": "Deal 100% SP to target row",
          "skill2cd":  "100",
          "autoname1": "Stun Resistance (M)",
          "auto1": "Increases Resistance against Stun Status by 90%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg1": "STUNresist",
          "autoname2": "SP up (M)",
          "auto2": "Increases own SP by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg2": "SPup",
          "autoname3": "",
          "auto3": "",
          "autoimg3": "",
          "autoname4": "Damage up (M)",
          "auto4": "Increases Damage given by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg4": "DMGup",
          "autoname5": "Damage Reduction (M)",
          "auto5": "Reduces Damage taken by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg5": "DMGresist",
          "lead": "Dex Type SP +5%",
          "rank": "G"
      },
            {
          "id": "10002",
          "name": "Kazuma Kuwabara, Sarayashiki School nº2",
          "type": "body",
          "class": "DEF",
          "rare": "3",
          "power": "365",
          "hp": "199",
          "atk": "108",
          "sp": "36",
          "def": "118",
          "spd": "44",
          "maxpower": "",
          "maxhp": "",
          "maxatk": "",
          "maxsp": "",
          "maxdef": "",
          "maxspd": "",
          "skill1img": "100003",
          "skill1name": "A Man's Sturdy Fist",
          "skill1": "Deal 160% SP to one enemy",
          "skill1cd":  "100",
          "skill2img": "100004",
          "skill2name": "Sharp Spiritual Intuition",
          "skill2": "+25% SP damage resistance to own row for 3 turns. blocks damage to self 1 time",
          "skill2cd":  "60",
          "autoname1": "Blind Resistance (M)",
          "auto1": "Increases Resistance against Blind Status by 90%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg1": "BLINDresist",
          "autoname2": "DEF up (M)",
          "auto2": "Increases own DEF by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg2": "DEFup",
          "autoname3": "",
          "auto3": "",
          "autoimg3": "",
          "autoname4": "Damage up (M)",
          "auto4": "Increases Damage given by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg4": "DMGup",
          "autoname5": "Damage Reduction (M)",
          "auto5": "Reduces Damage taken by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg5": "DMGresist",
          "lead": "Body Type DEF +5%",
          "rank": "G"
      },
         {
          "id": "10003",
          "name": "Kurama, Gratitude Heart",
          "type": "heart",
          "class": "ATK",
          "rare": "3",
          "power": "366",
          "hp": "162",
          "atk": "171",
          "sp": "36",
          "def": "72",
          "spd": "67",
          "maxpower": "",
          "maxhp": "",
          "maxatk": "",
          "maxsp": "",
          "maxdef": "",
          "maxspd": "",
          "skill1img": "100005",
          "skill1name": "Rose Whiplash",
          "skill1": "Deal 110% ATK to target with 80% chance to reduce DEF by 25% for 2 turns",
          "skill1cd":  "100",
          "skill2img": "100006",
          "skill2name": "Rose Whip",
          "skill2": "Deal 70% ATK to enemy back row",
          "skill2cd":  "100",
          "autoname1": "Silence Resistance (M)",
          "auto1": "Increases Resistance against Silence Status by 90%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg1": "SILENCEresist",
          "autoname2": "ATK up (M)",
          "auto2": "Increases own ATK by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg2": "ATKup",
          "autoname3": "",
          "auto3": "",
          "autoimg3": "",
          "autoname4": "Damage up (M)",
          "auto4": "Increases Damage given by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg4": "DMGup",
          "autoname5": "Damage Reduction (M)",
          "auto5": "Reduces Damage taken by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg5": "DMGresist",
          "lead": "Heart Type ATK +5%",
          "rank": "G"
      },
            {
          "id": "10004",
          "name": "Hiei, Master of the Evil Eye",
          "type": "yin",
          "class": "SP",
          "rare": "3",
          "power": "371",
          "hp": "181",
          "atk": "36",
          "sp": "145",
          "def": "90",
          "spd": "100",
          "maxpower": "",
          "maxhp": "",
          "maxatk": "",
          "maxsp": "",
          "maxdef": "",
          "maxspd": "",
          "skill1img": "100007",
          "skill1name": "Shadowless Fast Sword",
          "skill1": "Deal 160% SP to target",
          "skill1cd":  "100",
          "skill2img": "100008",
          "skill2name": "Spiritual Awakening",
          "skill2": "+30% SP to own column for 3 turns",
          "skill2cd":  "60",
          "autoname1": "Paralyze Resistance (M)",
          "auto1": "Increases Resistance against Paralyze Status by 90%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg1": "PARAresist",
          "autoname2": "SP up (M)",
          "auto2": "Increases own SP by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg2": "SPup",
          "autoname3": "",
          "auto3": "",
          "autoimg3": "",
          "autoname4": "Damage up (M)",
          "auto4": "Increases Damage given by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg4": "DMGup",
          "autoname5": "Damage Reduction (M)",
          "auto5": "Reduces Damage taken by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg5": "DMGresist",
          "lead": "Yin Type SP +5%",
          "rank": "G"
      },
          {
          "id": "10006",
          "name": "Gouki, Spirit-Sucking Demon",
          "type": "yin",
          "class": "ATK",
          "rare": "3",
          "power": "365",
          "hp": "181",
          "atk": "144",
          "sp": "36",
          "def": "90",
          "spd": "50",
          "maxpower": "",
          "maxhp": "",
          "maxatk": "",
          "maxsp": "",
          "maxdef": "",
          "maxspd": "",
          "skill1img": "100013",
          "skill1name": "Sudden Steel Motion",
          "skill1": "Deal 70% ATK to target row with 70% chance to reduce DEF by 15% for 2 turns",
          "skill1cd":  "100",
          "skill2img": "100014",
          "skill2name": "Big Log Stab",
          "skill2": "Deal 100% ATK to front row",
          "skill2cd":  "100",
          "autoname1": "Stun Resistance (M)",
          "auto1": "Increases Resistance against Stun Status by 90%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg1": "STUNresist",
          "autoname2": "ATK up (M)",
          "auto2": "Increases own ATK by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg2": "ATKup",
          "autoname3": "",
          "auto3": "",
          "autoimg3": "",
          "autoname4": "Damage up (M)",
          "auto4": "Increases Damage given by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg4": "DMGup",
          "autoname5": "Damage Reduction (M)",
          "auto5": "Reduces Damage taken by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg5": "DMGresist",
          "lead": "Yin Type ATK +5%",
          "rank": "G"
      },
  {
          "id": "10008",
          "name": "Genkai, Spirit Transmitter",
          "type": "yang",
          "class": "SP",
          "rare": "3",
          "power": "37",
          "hp": "168",
          "atk": "144",
          "sp": "177",
          "def": "74",
          "spd": "99",
          "maxpower": "",
          "maxhp": "",
          "maxatk": "",
          "maxsp": "",
          "maxdef": "",
          "maxspd": "",
          "skill1img": "100015",
          "skill1name": "Scolding",
          "skill1": "Deal 100% SP to front row",
          "skill1cd":  "100",
          "skill2img": "100016",
          "skill2name": "Spirit Bullet Scatter",
          "skill2": "Deal 40% SP to all enemies",
          "skill2cd":  "100",
          "autoname1": "Stun Resistance (M)",
          "auto1": "Increases Resistance against Stun Status by 90%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg1": "STUNresist",
          "autoname2": "SP up (M)",
          "auto2": "Increases own SP by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg2": "SPup",
          "autoname3": "",
          "auto3": "",
          "autoimg3": "",
          "autoname4": "Damage up (M)",
          "auto4": "Increases Damage given by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg4": "DMGup",
          "autoname5": "Damage Reduction (M)",
          "auto5": "Reduces Damage taken by 15%<br><hz>Duration:</hz> permanent <hz>Condition:</hz> at the start of the battle <hz>Chance:</hz> 100%",
          "autoimg5": "DMGresist",
          "lead": "Yang Type SP +5%",
          "rank": "G"
      },
] 
