window.chara=[
      {
          "id": "10015",
          "name": "Rando, Martial Arts Expert",
          "type": "heart",
          "class": "DEF",
          "rare": "5",
          "power": "1012",
          "hp": "554",
          "atk": "100",
          "sp": "301",
          "def": "327",
          "spd": "75",
          "skill1img": "100029",
          "skill1name": "Life Force Tread",
          "skill1": "50% chance to Paralyze target row for 1 turn. 80% chance to lower ATK by 25% for 3 turns",
          "skill1cd":  "70",
          "skill2img": "100030",
          "skill2name": "Hate Fish Summoning",
          "skill2": "Deal 120% SP to target row",
          "skill2cd":  "100",
          "autoname1": "ATK Damage Resistance (big)",
          "auto1": "Increases Resistance against ATK Damage taken by 20% permanently at the start of the battle",
          "autoimg1": "ATKDMGresist",
          "autoname2": "Paralyze Resistance",
          "auto2": "Increases Paralyze Resistance by 100% permanently at the start of the battle",
          "autoimg2": "PARAresist",
          "autoname3": "",
          "auto3": "",
          "autoimg3": "",
          "autoname4": "Damage up (big)",
          "auto4": "Increases Damage given by 20% permanently at the start of the battle",
          "autoimg4": "DMGup",
          "autoname5": "Damage Reduction (big)",
          "auto5": "+20% Damage Reduction",
          "autoimg5": "DMGredu",
          "lead": "Heart Type DEF +15%",
          "rank": "G"
      },
      {
          "id": "10023",
          "name": "Rinku, Magical Child",
          "type": "yang",
          "class": "ATK",
          "rare": "5",
          "power": "1056",
          "hp": "523",
          "atk": "418",
          "sp": "104",
          "def": "261",
          "spd": "123",
          "skill1name": "Serpent Yo-Yo",
          "skill1": "Deal 85% ATK to the front column. 40% chance to Paralyze for 1 turn",
          "skill1cd":  "110",
          "skill2name": "Nimble Body",
          "skill2": "Own row ATK +65% for 3 turns. +2 Basic Attack Dodge to self",
          "skill2cd":  "60",
          "auto1": "+100% Paralyze Resistance",
          "auto2": "+25% ATK",
          "auto3": "",
          "auto4": "+20% Damage",
          "auto5": "+20% Damage Reduction",
          "lead": "Yang Type ATK +15%",
          "rank": "G"
      },
      {
          "id": "10035",
          "name": "Jin, Wind User",
          "type": "heart",
          "class": "ATK",
          "rare": "5",
          "power": "1049",
          "hp": "518",
          "atk": "415",
          "sp": "103",
          "def": "258",
          "spd": "141",
          "skill1name": "Tornado Fist",
          "skill1": "Deal 180% ATK one enemy",
          "skill1cd":  "100",
          "skill2name": "Wind Barrier",
          "skill2": "Own column ATK +30% for 3 turns. +2 Basic Attack Dodge to self",
          "skill2cd":  "60",
          "auto1": "+25% ATK",
          "auto2": "+100% Stun Resistance",
          "auto3": "",
          "auto4": "+20% Damage",
          "auto5": "+20% Damage Reduction",
          "lead": "Heart Type ATK +15%",
          "rank": "G"
      },
      {
          "id": "10037",
          "name": "Toya, Curse Ice User",
          "type": "body",
          "class": "SP",
          "rare": "5",
          "power": "1035",
          "hp": "410",
          "atk": "102",
          "sp": "539",
          "def": "179",
          "spd": "105",
          "skill1name": "Ice Cutlass",
          "skill1": "Deal 180% SP one enemy",
          "skill1cd":  "100",
          "skill2name": "Shards of Winter",
          "skill2": "Deal 85% SP to the front column with a 40% Chance to Freeze for 1 turn",
          "skill2cd":  "110",
          "auto1": "+100% Freeze Resistance",
          "auto2": "+25% SP",
          "auto3": "",
          "auto4": "+20% Damage",
          "auto5": "+20% Damage Reduction",
          "lead": "Body Type SP +15%",
          "rank": "G"
      },
      {
          "id": "10043",
          "name": "Shishiwakamaru, Beautiful White Blade",
          "type": "yin",
          "class": "ATK",
          "rare": "5",
          "power": "1045",
          "hp": "518",
          "atk": "414",
          "sp": "103",
          "def": "259",
          "spd": "106",
          "skill1name": "Shukuchi",
          "skill1": "Own column Crit Chance +30% for 3 turns. +2 Basic Attack dodge to self",
          "skill1cd":  "60",
          "skill2name": "Chorus of a Thousand Skulls",
          "skill2": "Deal 85% ATK to front column with a 65% chance to inflict 10% Poison",
          "skill2cd":  "110",
          "auto1": "+20% Crit Chance",
          "auto2": "+100% Darkness Resistance",
          "auto3": "",
          "auto4": "+20% Damage",
          "auto5": "+20% Damage Reduction",
          "lead": "Yin Type ATK +15%",
          "rank": "G"
      },
      {
          "id": "10044",
          "name": "Beautiful Suzuki, Clown",
          "type": "dex",
          "class": "DEF",
          "rare": "5",
          "power": "1045",
          "hp": "570",
          "atk": "103",
          "sp": "310",
          "def": "337",
          "spd": "100",
          "skill1name": "Rainbow Cyclone",
          "skill1": "Deal 65% to the back column with a 80% chance to reduce SP by 25% for 3 turns",
          "skill1cd":  "100",
          "skill2name": "Body of Steel Muscle Explosion",
          "skill2": "Own column SP Damage Resistance +50% for 3 turns",
          "skill2cd":  "60",
          "auto1": "+100% Poison Resistance",
          "auto2": "+20% SP Damage Resistance",
          "auto3": "",
          "auto4": "+20% Damage",
          "auto5": "+20% Damage Reduction",
          "lead": "Dex Type DEF +15%",
          "rank": "G"
      },
      {
          "id": "10045",
          "name": "Genkai, Extreme Polished Warrior",
          "type": "yang",
          "class": "SP",
          "rare": "5",
          "power": "1058",
          "hp": "419",
          "atk": "104",
          "sp": "550",
          "def": "183",
          "spd": "115",
          "skill1name": "Spirit Wave Orb",
          "skill1": "All allies SP +25% for 2 turns. Overall Damage +25% for 2 turns",
          "skill1cd":  "60",
          "skill2name": "Spirit Gun: Weapon",
          "skill2": "Deal 120% SP to target row",
          "skill2cd":  "100",
          "auto1": "+25% SP",
          "auto2": "+100% Silence Resistance",
          "auto3": "+50% SP to all allies for 2 turns upon death",
          "auto4": "+20% Damage",
          "auto5": "+20% Damage Reduction",
          "lead": "Yang Type SP +15%",
          "rank": "G"
      },
      {
          "id": "10046",
          "name": "Yusuke Urameshi, Spirit's Successor",
          "type": "heart",
          "class": "SP",
          "rare": "5",
          "power": "1055",
          "hp": "419",
          "atk": "104",
          "sp": "549",
          "def": "183",
          "spd": "95",
          "skill1name": "Spirit Gun: Light",
          "skill1": "Deal 50% SP to all enemy",
          "skill1cd":  "100",
          "skill2name": "Spirit Wave",
          "skill2": "Deal 110% SP to one enemy. Deal more damage when own HP is lower. (Maximum +150%)",
          "skill2cd":  "100",
          "auto1": "+100% Burn Resistance",
          "auto2": "+25% SP",
          "auto3": "+50% Heart Damage when for 2 turns when HP reach below 30% once",
          "auto4": "+20% Damage",
          "auto5": "+20% Damage Reduction",
          "lead": "Heart Type SP +15%",
          "rank": "G"
      },
      {
          "id": "10047",
          "name": "Kazuma Kuwabara, Flower Fantasy",
          "type": "yang",
          "class": "ATK",
          "rare": "5",
          "power": "1042",
          "hp": "415",
          "atk": "544",
          "sp": "103",
          "def": "181",
          "spd": "68",
          "skill1name": "Spirit Flyswatter",
          "skill1": "Deal 85% ATK to front column with a 40% Chance to Stun for 1 turn",
          "skill1cd":  "110",
          "skill2name": "Spirit Sword Shards",
          "skill2": "Deal 180% ATK to one enemy",
          "skill2cd":  "100",
          "auto1": "+25% ATK",
          "auto2": "+100% Stun Resistance",
          "auto3": "",
          "auto4": "+20% Damage",
          "auto5": "+20% Damage Reduction",
          "lead": "Yang Type ATK +15%",
          "rank": "G"
      },
      {
          "id": "10048",
          "name": "Kurama, Dazzling",
          "type": "body",
          "class": "DEF",
          "rare": "5",
          "power": "1044",
          "hp": "571",
          "atk": "310",
          "sp": "103",
          "def": "337",
          "spd": "90",
          "skill1name": "Rose Whip Thorn Wheel",
          "skill1": "All allies ATK Damage Resistance +25% for 2 turns. +25% DEF for 2 turns",
          "skill1cd":  "60",
          "skill2name": "Bloodsucking Plant",
          "skill2": "Deal 125% ATK to one enemy with a 90% chance to inflict 10% Poison for 2 turns",
          "skill2cd":  "110",
          "auto1": "+25% ATK Damage Resistance",
          "auto2": "+100% Poison Resistance",
          "auto3": "+50% HP once when HP reach below 50%",
          "auto4": "+20% Damage",
          "auto5": "+20% Damage Reduction",
          "lead": "Body Type DEF +15%",
          "rank": "G"
      },
      {
          "id": "10050",
          "name": "Hiei, Single Stroke",
          "type": "dex",
          "class": "SP",
          "rare": "5",
          "power": "1053",
          "hp": "414",
          "atk": "103",
          "sp": "545",
          "def": "181",
          "spd": "170",
          "skill1name": "Dragon of Darkness Flame",
          "skill1": "Deal 170% SP to target row. 90% chance to inflict 10% Burn for 2 turns. Silence self for 2 turns",
          "skill1cd":  "130",
          "skill2name": "Sword of Darkness Flames",
          "skill2": "Deal 180% SP to one enemy",
          "skill2cd":  "100",
          "auto1": "+25% Advantage Damage",
          "auto2": "+100% Burn Resistance",
          "auto3": "+50% SP for 2 turns at the start of the WAVE",
          "auto4": "+20% Damage",
          "auto5": "+20% Damage Reduction",
          "lead": "Dex Type SP +15%",
          "rank": "G"
      },
      {
          "id": "10051",
          "name": "Karasu, Beautiful Dark Evil",
          "type": "yin",
          "class": "ATK",
          "rare": "5",
          "power": "1049",
          "hp": "415",
          "atk": "544",
          "sp": "103",
          "def": "181",
          "spd": "141",
          "skill1name": "Trace Eyes",
          "skill1": "Deal 125% ATK to one enemy with a 90% chance to inflict 10% Burn",
          "skill1cd":  "110",
          "skill2name": "Time Bomb",
          "skill2": "Deal 85% ATK to front column with a 25% chance to lower DEF for 3 turns",
          "skill2cd":  "100",
          "auto1": "+25% ATK",
          "auto2": "+100% Freeze Resistance",
          "auto3": "",
          "auto4": "+20% Damage",
          "auto5": "+20% Damage Reduction",
          "lead": "Yin Type ATK +15%",
          "rank": "G"
      }, 
      {
          "id": "10052",
          "name": "Bui, Large Axe and Heavy Armor",
          "type": "dex",
          "class": "ATK",
          "rare": "5",
          "power": "1046",
          "hp": "518",
          "atk": "415",
          "sp": "103",
          "def": "259",
          "spd": "106",
          "skill1name": "Stone Throw",
          "skill1": "Deal 125% ATK to one enemy with a 70% chance to Stun for 1 turn",
          "skill1cd":  "110",
          "skill2name": "Tomahawk Ax",
          "skill2": "Deal 85% ATK to target row with a 80% chance to reduce ATK Damage Resistance by 25% for 3 turns",
          "skill2cd":  "100",
          "auto1": "+25% ATK",
          "auto2": "+100% Darkness Resistance",
          "auto3": "",
          "auto4": "+20% Damage",
          "auto5": "+20% Damage Reduction",
          "lead": "Dex Type ATK +15%",
          "rank": "G"
      },
      {
          "id": "10053",
          "name": "Elder Toguro, Brutal Sweep",
          "type": "yang",
          "class": "SP",
          "rare": "5",
          "power": "14999",
          "hp": "7484",
          "atk": "1496",
          "sp": "5996",
          "def": "3728",
          "spd": "375",
          "skill1name": "Mimicry",
          "skill1": "Own column +40% Yang Damage. +20% HP regen for 3 turns",
          "skill1cd":  "70",
          "skill2name": "Weaponized Body",
          "skill2": "Deal +50% SP to all enemies",
          "skill2cd":  "100",
          "auto1": "+25% SP",
          "auto2": "+100% Stun Resistance",
          "auto3": "+15% HP upon death twice",
          "auto4": "+20% Damage",
          "auto5": "+20% Damage Reduction",
          "lead": "Yang Type SP +15%",
          "rank": "SSS"
      },
      {
          "id": "10054",
          "name": "Younger Toguro, Super Powered Butcher",
          "type": "body",
          "class": "ATK",
          "rare": "5",
          "power": "1053",
          "hp": "524",
          "atk": "419",
          "sp": "104",
          "def": "261",
          "spd": "74",
          "skill1name": "Super Powered Blow",
          "skill1": "Deal 110% ATK to one enemy. Deal more damage when own HP is higher (+100%)",
          "skill1cd":  "110",
          "skill2name": "Acidity Atmosphere",
          "skill2": "40% chance to inflict 10% Burn to front column for 2 turns. 80% chance to reduce ATK damage Resistance by 25% for 3 turns",
          "skill2cd":  "70",
          "auto1": "+20% Crit Chance",
          "auto2": "+100% Stun Resistance",
          "auto3": "30% chance for +30% ATK for 2 turns after using a Special",
          "auto4": "+20% Damage",
          "auto5": "+20% Damage Reduction",
          "lead": "Body Type ATK +15%",
          "rank": "G"
      },
      {
          "id": "10055",
          "name": "Younger Toguro, Leaking Evil",
          "type": "yin",
          "class": "ATK",
          "rare": "5",
          "power": "15066",
          "hp": "6024",
          "atk": "7908",
          "sp": "2624",
          "def": "1496",
          "spd": "268",
          "skill1name": "Shidan",
          "skill1": "Deal 120% ATK to target row.",
          "skill1cd":  "100",
          "skill2name": "Threat of a Superior Class",
          "skill2": "Deal 60% ATK to all enemies with a 70% chance to reduce enemy's ATK Damage Resistance by 20% for 2 turns. Own ATK -50% for 2 turns",
          "skill2cd":  "120",
          "auto1": "+25% Advantage Damage",
          "auto2": "+100% Poison Resistance",
          "auto3": "50% chance for +100% ATK for 2 turns after defeating an enemy",
          "auto4": "+20% Damage",
          "auto5": "+20% Damage Reduction",
          "lead": "Yang Type SP +15%",
          "rank": "SSS"
      },
      {
          "id": "10127",
          "name": "Chu, Drunken Style Fighter",
          "type": "yin",
          "class": "SP",
          "rare": "5",
          "power": "1041",
          "hp": "410",
          "atk": "102",
          "sp": "540",
          "def": "179",
          "spd": "150",
          "skill1name": "Drink Enhancement",
          "skill1": "Own row SP +40% for 3 turns. +40% advantage damage for 3 turns",
          "skill1cd":  "60",
          "skill2name": "Ogre Boulder]",
          "skill2": "Deal 120% SP to front column",
          "skill2cd":  "100",
          "auto1": "+100% Stun Resistance",
          "auto2": "+25% SP",
          "auto3": "",
          "auto4": "+20% Damage",
          "auto5": "+20% Damage Reduction",
          "lead": "Yin Type SP +15%",
          "rank": "G"
      },  
] 
