window.support=[
     
            // -------------------------------------------------------------------------------- 
                                              // 5 STAR CARDS
            // -------------------------------------------------------------------------------- 
     
     {
          "id": "20001",
          "name": "Keiko Yukimura, Goddess of Victory",
          "type": "heart",
          "class": "ATK",
          "rare": "5",
          "power": "1012",
          "hp": "500",
          "atk": "400",
          "sp": "100",
          "def": "250",
          "spd": "121",
          "maxpower": "14327",
          "maxhp": "7140",
          "maxatk": "5712",
          "maxsp": "1428",
          "maxdef": "3572",
          "maxspd": "450",
          "skillname": "ATK up",
          "skill": "Increases ATK of equipped unit by 80%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> after defeating an enemy <hz>Chance:</hz> 80%",
          "skillimg": "ATKup",
     },
     {
          "id": "20002",
          "name": "Botan, Spiritual Guide",
          "type": "yang",
          "class": "SP",
          "rare": "5",
          "power": "1011",
          "hp": "400",
          "atk": "100",
          "sp": "525",
          "def": "175",
          "spd": "111",
          "maxpower": "14317",
          "maxhp": "5712",
          "maxsp": "1428",
          "maxatk": "1428",
          "maxdef": "7496",
          "maxspd": "412",
          "skillname": "SP up",
          "skill": "Increases SP of equipped column by 24%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> start of the WAVE <hz>Chance:</hz> 100%",
          "skillimg": "ATKup",
     },
     {
          "id": "20016",
          "name": "Yukina, Dearly Prayer",
          "type": "body",
          "class": "DEF",
          "rare": "5",
          "power": "1011",
          "hp": "550",
          "atk": "200",
          "def": "325",
          "sp": "200",
          "spd": "119",
          "maxpower": "-",
          "maxhp": "-",
          "maxatk": "-",
          "maxsp": "-",
          "maxdef": "-",
          "maxspd": "-",
          "skillname": "Heal",
          "skill": "Heals equipped unit's HP by 50%<br><hz>Duration:</hz> instant <hz>Condition:</hz> when HP is under 50% <hz>Chance:</hz> 100%",
          "skillimg": "HEAL",
     },
     {
          "id": "20019",
          "name": "Sakyo, A Game of Aesthetics",
          "type": "yin",
          "class": "SP",
          "rare": "5",
          "power": "1012",
          "hp": "500",
          "atk": "100",
          "sp": "400",
          "def": "250",
          "spd": "126",
          "maxpower": "14328",
          "maxhp": "7140",
          "maxatk": "1428",
          "maxsp": "5712",
          "maxdef": "3572",
          "maxspd": "468",
          "skillname": "Defense Down",
          "skill": "Decreases DEF of front enemy column by 43%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> after a status decrease <hz>Chance:</hz> 80%",
          "skillimg": "DEFdown",
     },
     {
          "id": "20024",
          "name": "Koenma (Youth), Spirit World Royalty",
          "type": "dex",
          "class": "DEF",
          "rare": "5",
          "power": "1012",
          "hp": "550",
          "atk": "100",
          "sp": "300",
          "def": "325",
          "spd": "120",
          "maxpower": "14324",
          "maxhp": "7856",
          "maxatk": "1428",
          "maxsp": "4284",
          "maxdef": "4640",
          "maxspd": "446",
          "skillname": "Ressurection",
          "skill": "Revives equipped unit with 29% HP<br><hz>Duration:</hz> instant <hz>Condition:</hz> upon death <hz>Chance:</hz> 100%/1 time",
          "skillimg": "REVIVE",
     },
     
            // -------------------------------------------------------------------------------- 
                                              // 4 STAR CARDS
            // -------------------------------------------------------------------------------- 
     
     {
          "id": "20003",
          "name": "Koenma, Enma's Son",
          "type": "body",
          "class": "ATK",
          "rare": "4",
          "power": "491",
          "hp": "192",
          "atk": "252",
          "def": "84",
          "sp": "48",
          "spd": "112",
          "maxpower": "-",
          "maxhp": "-",
          "maxatk": "-",
          "maxsp": "-",
          "maxdef": "-",
          "maxspd": "-",
          "skillname": "Atk Up",
          "skill": "Increases ATK of equipped unit by 40%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> when HP is under 50% <hz>Chance:</hz> 90%/1 time",
          "skillimg": "ATKup",
     },
     
     {
          "id": "20006",
          "name": "Atsuko Urameshi, Bad Housewife",
          "type": "heart",
          "class": "ATK",
          "rare": "4",
          "power": "491",
          "hp": "240",
          "atk": "192",
          "def": "120",
          "sp": "48",
          "spd": "119",
          "maxpower": "-",
          "maxhp": "-",
          "maxatk": "-",
          "maxsp": "-",
          "maxdef": "-",
          "maxspd": "-",
          "skillname": "Critical Up",
          "skill": "Increases Critical Rate of equipped unit by 19%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> after a status decrease <hz>Chance:</hz> 72%",
          "skillimg": "CRITup",
     },
     
     {
          "id": "20012",
          "name": "Ayame, Secret Feelings",
          "type": "yin",
          "class": "DEF",
          "rare": "4",
          "power": "491",
          "hp": "264",
          "atk": "96",
          "def": "156",
          "sp": "96",
          "spd": "119",
          "maxpower": "-",
          "maxhp": "-",
          "maxatk": "-",
          "maxsp": "-",
          "maxdef": "-",
          "maxspd": "-",
          "skillname": "Heal",
          "skill": "Heals equipped unit's HP by 24%<br><hz>Duration:</hz> instant <hz>Condition:</hz> when HP is under 30% <hz>Chance:</hz> 80%/1 time",
          "skillimg": "HEAL",
     },
     
     {
          "id": "20014",
          "name": "Shizuru Kuwabara, Spirit Sensing Elder Sister",
          "type": "dex",
          "class": "SP",
          "rare": "4",
          "power": "491",
          "hp": "216",
          "atk": "48",
          "def": "96",
          "sp": "228",
          "spd": "116",
          "maxpower": "-",
          "maxhp": "-",
          "maxatk": "-",
          "maxsp": "-",
          "maxdef": "-",
          "maxspd": "-",
          "skillname": "SP up",
          "skill": "Increases SP of equipped unit by 24%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> after defeating an enemy <hz>Chance:</hz> 72%",
          "skillimg": "HEAL",
     },
     
     {
          "id": "20051",
          "name": "Puu, Words of the Master",
          "type": "yang",
          "class": "DEF",
          "rare": "4",
          "power": "491",
          "hp": "264",
          "atk": "48",
          "def": "156",
          "sp": "144",
          "spd": "114",
          "maxpower": "-",
          "maxhp": "-",
          "maxatk": "-",
          "maxsp": "-",
          "maxdef": "-",
          "maxspd": "-",
          "skillname": "ATK Damage Resistance",
          "skill": "Increases Resistance of equipped row against ATK Damage taken by 30%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> when HP is under 50% <hz>Chance:</hz> 90%/1 time",
          "skillimg": "ATKDMGresist",
     },
     
            // -------------------------------------------------------------------------------- 
                                              // 3 STAR CARDS
            // -------------------------------------------------------------------------------- 
     
     {
          "id": "20004",
          "name": "Sayaka, Spirit World Agent",
          "type": "yang",
          "class": "DEF",
          "rare": "3",
          "power": "372",
          "hp": "198",
          "atk": "72",
          "def": "117",
          "sp": "72",
          "spd": "125",
          "maxpower": "-",
          "maxhp": "-",
          "maxatk": "-",
          "maxsp": "-",
          "maxdef": "-",
          "maxspd": "-",
          "skillname": "HEAL",
          "skill": "Heals equipped unit's HP by 21%<br><hz>Duration:</hz> instant <hz>Condition:</hz> when HP is under 30% <hz>Chance:</hz> 70%/1 time",
          "skillimg": "HEAL",
     },
     
     {
          "id": "20011",
          "name": "George Saotome, Honest Assistant",
          "type": "body",
          "class": "SP",
          "rare": "3",
          "power": "371",
          "hp": "180",
          "atk": "36",
          "def": "90",
          "sp": "144",
          "spd": "112",
          "maxpower": "-",
          "maxhp": "-",
          "maxatk": "-",
          "maxsp": "-",
          "maxdef": "-",
          "maxspd": "-",
          "skillname": "Sp Up",
          "skill": "Increases SP of equipped unit by 21%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> at the start of the WAVE <hz>Chance:</hz> 80%",
          "skillimg": "SPup",
     },
     
     {
          "id": "20017",
          "name": "Puu, Spirit Beast",
          "type": "heart",
          "class": "DEF",
          "rare": "3",
          "power": "371",
          "hp": "198",
          "atk": "108",
          "def": "117",
          "sp": "36",
          "spd": "114",
          "maxpower": "-",
          "maxhp": "-",
          "maxatk": "-",
          "maxsp": "-",
          "maxdef": "-",
          "maxspd": "-",
          "skillname": "Sp Damage Resistance",
          "skill": "Increases resistance of equipped unit against SP damage taken by 35%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> when HP is under 50% <hz>Chance:</hz> 80%/1 time",
          "skillimg": "SPDMGresist",
     },
     
     {
          "id": "20026",
          "name": "Shiori Minamino, Gentle Mother",
          "type": "dex",
          "class": "DEF",
          "rare": "3",
          "power": "372",
          "hp": "198",
          "atk": "72",
          "def": "117",
          "sp": "72",
          "spd": "124",
          "maxpower": "-",
          "maxhp": "-",
          "maxatk": "-",
          "maxsp": "-",
          "maxdef": "-",
          "maxspd": "-",
          "skillname": "Defense Up",
          "skill": "Increases DEF of equipped unit by 21%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> at the start of the WAVE <hz>Chance:</hz> 80%",
          "skillimg": "DEFup",
     },
     
     {
          "id": "20058",
          "name": "Hagiri's Younger Sister, Psychometry",
          "type": "yin",
          "class": "ATK",
          "rare": "3",
          "power": "371",
          "hp": "161",
          "atk": "72",
          "def": "171",
          "sp": "36",
          "spd": "116",
          "maxpower": "-",
          "maxhp": "-",
          "maxatk": "-",
          "maxsp": "-",
          "maxdef": "-",
          "maxspd": "-",
          "skillname": "Defense Down",
          "skill": "80% chance of decreasing target's DEF by 21%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> when hit by a special <hz>Chance:</hz> 64%",
          "skillimg": "DEFdown",
     },
            // -------------------------------------------------------------------------------- 
                                              // 2 STAR CARDS
            // -------------------------------------------------------------------------------- 
     
     {
          "id": "20018",
          "name": "Muguru, Bird Demon",
          "type": "heart",
          "class": "SP",
          "rare": "2",
          "power": "292",
          "hp": "126",
          "atk": "26",
          "def": "56",
          "sp": "133",
          "spd": "128",
          "maxpower": "-",
          "maxhp": "-",
          "maxatk": "-",
          "maxsp": "-",
          "maxdef": "-",
          "maxspd": "-",
          "skillname": "SP Damage Resistance Down",
          "skill": "80% chance of decreasing target's resistance against SP damage taken by 21%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> when hit by a special <hz>Chance:</hz> 64%",
          "skillimg": "SPDMGresist",
     },
     
     {
          "id": "20029",
          "name": "Okubo, Kuwabara's Underling",
          "type": "yin",
          "class": "DEF",
          "rare": "2",
          "power": "291",
          "hp": "154",
          "atk": "56",
          "def": "91",
          "sp": "56",
          "spd": "113",
          "maxpower": "-",
          "maxhp": "-",
          "maxatk": "-",
          "maxsp": "-",
          "maxdef": "-",
          "maxspd": "-",
          "skillname": "Def Up",
          "skill": "Increases DEF of equipped unit by 35%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> when HP is under 50% <hz>Chance:</hz> 80%/1 time",
          "skillimg": "DEFup",
     },
     
     {
          "id": "20030",
          "name": "Kirishima, Kuwabara's Underling",
          "type": "dex",
          "class": "ATK",
          "rare": "2",
          "power": "291",
          "hp": "140",
          "atk": "112",
          "def": "70",
          "sp": "28",
          "spd": "119",
          "maxpower": "-",
          "maxhp": "-",
          "maxatk": "-",
          "maxsp": "-",
          "maxdef": "-",
          "maxspd": "-",
          "skillname": "Atk Up",
          "skill": "Increases ATK of equipped unit by 35%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> when HP is under 50% <hz>Chance:</hz> 80%/1 time",
          "skillimg": "ATKup",
     },
     
     {
          "id": "20031",
          "name": "Sawamura, Kuwabara's Underling",
          "type": "yang",
          "class": "DEF",
          "rare": "2",
          "power": "292",
          "hp": "154",
          "atk": "56",
          "def": "91",
          "sp": "56",
          "spd": "126",
          "maxpower": "-",
          "maxhp": "-",
          "maxatk": "-",
          "maxsp": "-",
          "maxdef": "-",
          "maxspd": "-",
          "skillname": "Def Up",
          "skill": "Increases DEF of equipped unit by 28%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> after a status decrease <hz>Chance:</hz> 64%",
          "skillimg": "DEFup",
     },
     
     {
          "id": "20045",
          "name": "Ship's Captain, Guide",
          "type": "body",
          "class": "ATK",
          "rare": "2",
          "power": "291",
          "hp": "126",
          "atk": "133",
          "def": "56",
          "sp": "28",
          "spd": "111",
          "maxpower": "-",
          "maxhp": "-",
          "maxatk": "-",
          "maxsp": "-",
          "maxdef": "-",
          "maxspd": "-",
          "skillname": "Atk Up",
          "skill": "Increases ATK of equipped unit by 28%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> when an ally dies <hz>Chance:</hz> 80%",
          "skillimg": "ATKup",
     },
     
            // -------------------------------------------------------------------------------- 
                                              // 1 STAR CARDS
            // -------------------------------------------------------------------------------- 
     
     {
          "id": "20005",
          "name": "Takenaka, Model Teacher",
          "type": "heart",
          "class": "ATK",
          "rare": "1",
          "power": "252",
          "hp": "120",
          "atk": "96",
          "def": "60",
          "sp": "24",
          "spd": "121",
          "maxpower": "-",
          "maxhp": "-",
          "maxatk": "-",
          "maxsp": "-",
          "maxdef": "-",
          "maxspd": "-",
          "skillname": "Atk Up",
          "skill": "Increases ATK of equipped unit by 21%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> at the start of the WAVE <hz>Chance:</hz> 80%",
          "skillimg": "ATKup",
     },
     
     {
          "id": "20015",
          "name": "Eikichi, Kuwabara's Best Friend",
          "type": "yang",
          "class": "ATK",
          "rare": "1",
          "power": "252",
          "hp": "108",
          "atk": "114",
          "def": "48",
          "sp": "24",
          "spd": "126",
          "maxpower": "-",
          "maxhp": "-",
          "maxatk": "-",
          "maxsp": "-",
          "maxdef": "-",
          "maxspd": "-",
          "skillname": "Atk Damage Resistance Down",
          "skill": "80% chance of decreasing enemy's resistance against ATK damage taken by 21%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> when hit by a special <hz>Chance:</hz> 64%",
          "skillimg": "ATKDMGresistdown",
     },
     
     {
          "id": "20025",
          "name": "Little Girl, The Saved One",
          "type": "body",
          "class": "DEF",
          "rare": "1",
          "power": "251",
          "hp": "132",
          "atk": "72",
          "def": "78",
          "sp": "24",
          "spd": "116",
          "maxpower": "-",
          "maxhp": "-",
          "maxatk": "-",
          "maxsp": "-",
          "maxdef": "-",
          "maxspd": "-",
          "skillname": "Atk Damage Resistance Up",
          "skill": "Increases resistance of equipped unit against ATK damage taken by 28%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> after a status decrease <hz>Chance:</hz> 64%",
          "skillimg": "ATKDMGresist",
     },
     
     {
          "id": "20027",
          "name": "Iwamoto, Bad Teacher",
          "type": "yin",
          "class": "SP",
          "rare": "1",
          "power": "251",
          "hp": "108",
          "atk": "24",
          "def": "48",
          "sp": "114",
          "spd": "116",
          "maxpower": "-",
          "maxhp": "-",
          "maxatk": "-",
          "maxsp": "-",
          "maxdef": "-",
          "maxspd": "-",
          "skillname": "Atk Up",
          "skill": "Increases SP of equipped unit by 28%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> after a status decrease <hz>Chance:</hz> 64%",
          "skillimg": "SPup",
     },
     
     {
          "id": "20028",
          "name": "Akashi, Minion",
          "type": "dex",
          "class": "DEF",
          "rare": "1",
          "power": "251",
          "hp": "132",
          "atk": "24",
          "def": "78",
          "sp": "72",
          "spd": "111",
          "maxpower": "-",
          "maxhp": "-",
          "maxatk": "-",
          "maxsp": "-",
          "maxdef": "-",
          "maxspd": "-",
          "skillname": "Atk Damage Resistance Up",
          "skill": "Increases resistance of equipped unit against ATK damage taken by 28%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> when under a status condition <hz>Chance:</hz> 80%",
          "skillimg": "ATKDMGresist",
     },
     
] 
