window.support=[
     {
          "id": "20001",
          "name": "Keiko Yukimura, Goddess of Victory",
          "type": "heart",
          "class": "atk",
          "rare": "5",
          "power": "1012",
          "hp": "500",
          "atk": "400",
          "sp": "100",
          "def": "250",
          "spd": "121",
          "maxpower": "14327",
          "maxhp": "7140",
          "maxatk": "5712",
          "maxsp": "1428",
          "maxdef": "3572",
          "maxspd": "450",
          "skillname": "ATK up",
          "skill": "Increases ATK by 80% to equipped unit<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> after defeating an enemy <hz>Chance:</hz> 80%",
          "skillimg": "ATKup",
     },
     {
          "id": "20002",
          "name": "Botan, Spiritual Guide",
          "type": "yang",
          "class": "sp",
          "rare": "5",
          "power": "1011",
          "hp": "400",
          "atk": "100",
          "sp": "525",
          "def": "175",
          "spd": "111",
          "maxpower": "14317",
          "maxhp": "5712",
          "maxsp": "1428",
          "maxatk": "1428",
          "maxdef": "7496",
          "maxspd": "412",
          "skillname": "SP up",
          "skill": "Increases SP by 24% to equipped column<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> start of the WAVE <hz>Chance:</hz> 1000%",
          "skillimg": "ATKup",
     },
     {
          "id": "20019",
          "name": "Sakyo, Game Aesthetic",
          "type": "yin",
          "class": "SP",
          "rare": "5",
          "power": "1012",
          "hp": "500",
          "atk": "100",
          "sp": "400",
          "def": "250",
          "spd": "126",
          "maxpower": "14328",
          "maxhp": "7140",
          "maxatk": "1428",
          "maxsp": "5712",
          "maxdef": "3572",
          "maxspd": "468",
          "skillname": "",
          "skill": "80% chance to reduce the front enemy column by 43% for 3 turns",
     },
     {
          "id": "20024",
          "name": "Koenma (Youth), Prince of the Spiritual World",
          "type": "dex",
          "class": "DEF",
          "rare": "5",
          "power": "1012",
          "hp": "550",
          "atk": "100",
          "sp": "300",
          "def": "325",
          "spd": "120",
          "maxpower": "14324",
          "maxhp": "7856",
          "maxatk": "1428",
          "maxsp": "4284",
          "maxdef": "4640",
          "maxspd": "446",
          "skillname": "",
          "skill": "Recover 29% HP upon death once",
     },
] 
