window.support=[
     
            // -------------------------------------------------------------------------------- 
                                              // 5 STAR CARDS
            // -------------------------------------------------------------------------------- 
     
     {
          "id": "20001",
          "name": "Keiko Yukimura, Goddess of Victory",
          "type": "heart",
          "class": "ATK",
          "rare": "5",
          "power": "1012",
          "hp": "500",
          "atk": "400",
          "sp": "100",
          "def": "250",
          "spd": "121",
          "maxpower": "14327",
          "maxhp": "7140",
          "maxatk": "5712",
          "maxsp": "1428",
          "maxdef": "3572",
          "maxspd": "450",
          "skillname": "ATK up",
          "skill": "Increases ATK of equipped unit by 80%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> after defeating an enemy <hz>Chance:</hz> 80%",
          "skillimg": "ATKup",
     },
     {
          "id": "20002",
          "name": "Botan, Spiritual Guide",
          "type": "yang",
          "class": "SP",
          "rare": "5",
          "power": "1011",
          "hp": "400",
          "atk": "100",
          "sp": "525",
          "def": "175",
          "spd": "111",
          "maxpower": "14317",
          "maxhp": "5712",
          "maxsp": "1428",
          "maxatk": "1428",
          "maxdef": "7496",
          "maxspd": "412",
          "skillname": "SP up",
          "skill": "Increases SP of equipped column by 24%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> start of the WAVE <hz>Chance:</hz> 100%",
          "skillimg": "ATKup",
     },
     {
          "id": "20016",
          "name": "Yukina, Dearly Prayer",
          "type": "body",
          "class": "DEF",
          "rare": "5",
          "power": "1011",
          "hp": "550",
          "atk": "200",
          "def": "325",
          "sp": "200",
          "spd": "119",
          "maxpower": "-",
          "maxhp": "-",
          "maxatk": "-",
          "maxsp": "-",
          "maxdef": "-",
          "maxspd": "-",
          "skillname": "Heal",
          "skill": "Heals equipped unit's HP by 50%<br><hz>Duration:</hz> instant <hz>Condition:</hz> when HP is under 50% <hz>Chance:</hz> 100%",
          "skillimg": "HEAL",
     },
     {
          "id": "20019",
          "name": "Sakyo, A Game of Aesthetics",
          "type": "yin",
          "class": "SP",
          "rare": "5",
          "power": "1012",
          "hp": "500",
          "atk": "100",
          "sp": "400",
          "def": "250",
          "spd": "126",
          "maxpower": "14328",
          "maxhp": "7140",
          "maxatk": "1428",
          "maxsp": "5712",
          "maxdef": "3572",
          "maxspd": "468",
          "skillname": "Defense Down",
          "skill": "Decreases DEF of front enemy column by 43%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> after a status decrease <hz>Chance:</hz> 80%",
          "skillimg": "DEFdown",
     },
     {
          "id": "20024",
          "name": "Koenma (Youth), Spirit World Royalty",
          "type": "dex",
          "class": "DEF",
          "rare": "5",
          "power": "1012",
          "hp": "550",
          "atk": "100",
          "sp": "300",
          "def": "325",
          "spd": "120",
          "maxpower": "14324",
          "maxhp": "7856",
          "maxatk": "1428",
          "maxsp": "4284",
          "maxdef": "4640",
          "maxspd": "446",
          "skillname": "Ressurection",
          "skill": "Revives equipped unit with 29% HP<br><hz>Duration:</hz> instant <hz>Condition:</hz> upon death <hz>Chance:</hz> 100%/1 time",
          "skillimg": "REVIVE",
     },
     
            // -------------------------------------------------------------------------------- 
                                              // 4 STAR CARDS
            // -------------------------------------------------------------------------------- 
     
     {
          "id": "20003",
          "name": "Koenma, Enma's Son",
          "type": "body",
          "class": "ATK",
          "rare": "4",
          "power": "491",
          "hp": "192",
          "atk": "252",
          "def": "84",
          "sp": "48",
          "spd": "112",
          "maxpower": "-",
          "maxhp": "-",
          "maxatk": "-",
          "maxsp": "-",
          "maxdef": "-",
          "maxspd": "-",
          "skillname": "Atk Up",
          "skill": "Increases ATK of equipped unit by 40%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> when HP is under 50% <hz>Chance:</hz> 90%/1 time",
          "skillimg": "ATKup",
     },
     
     {
          "id": "20006",
          "name": "Atsuko Urameshi, Bad Housewife",
          "type": "heart",
          "class": "ATK",
          "rare": "4",
          "power": "491",
          "hp": "240",
          "atk": "192",
          "def": "120",
          "sp": "48",
          "spd": "119",
          "maxpower": "-",
          "maxhp": "-",
          "maxatk": "-",
          "maxsp": "-",
          "maxdef": "-",
          "maxspd": "-",
          "skillname": "Critical Up",
          "skill": "Increases Critical Rate of equipped unit by 19%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> after a status decrease <hz>Chance:</hz> 72%",
          "skillimg": "CRITup",
     },
     
     {
          "id": "20012",
          "name": "Ayame, Secret Feelings",
          "type": "yin",
          "class": "DEF",
          "rare": "4",
          "power": "491",
          "hp": "264",
          "atk": "96",
          "def": "156",
          "sp": "96",
          "spd": "119",
          "maxpower": "-",
          "maxhp": "-",
          "maxatk": "-",
          "maxsp": "-",
          "maxdef": "-",
          "maxspd": "-",
          "skillname": "Heal",
          "skill": "Heals equipped unit's HP by 24%<br><hz>Duration:</hz> instant <hz>Condition:</hz> when HP is under 30% <hz>Chance:</hz> 80%/1 time",
          "skillimg": "HEAL",
     },
     
     {
          "id": "20014",
          "name": "Shizuru Kuwabara, Spirit Sensing Elder Sister",
          "type": "dex",
          "class": "SP",
          "rare": "4",
          "power": "491",
          "hp": "216",
          "atk": "48",
          "def": "96",
          "sp": "228",
          "spd": "116",
          "maxpower": "-",
          "maxhp": "-",
          "maxatk": "-",
          "maxsp": "-",
          "maxdef": "-",
          "maxspd": "-",
          "skillname": "SP up",
          "skill": "Increases SP of equipped unit by 24%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> after defeating an enemy <hz>Chance:</hz> 72%",
          "skillimg": "HEAL",
     },
     
     {
          "id": "20051",
          "name": "Puu, Words of the Master",
          "type": "yang",
          "class": "DEF",
          "rare": "4",
          "power": "491",
          "hp": "264",
          "atk": "48",
          "def": "156",
          "sp": "144",
          "spd": "114",
          "maxpower": "-",
          "maxhp": "-",
          "maxatk": "-",
          "maxsp": "-",
          "maxdef": "-",
          "maxspd": "-",
          "skillname": "ATK Damage Resistance",
          "skill": "Increases Resistance of equipped row against ATK Damage taken by 30%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> when HP is under 50% <hz>Chance:</hz> 90%/1 time",
          "skillimg": "ATKDMGresist",
     },
     
] 
